---
format: 
    html:
        output-file: index.html
    docx:
        output-file: JH-chapter-abstract.docx
---
# Abstract {.unnumbered}


The lasting legacy of most medical research is the written account. Authors often miss out information needed by readers &mdash; including clinicians, reviewers, patients, and other researchers &mdash; need to fully understand, appraise, replicate, or apply the research. Reporting guidelines try to solve this problem. They are community-created recommendations for information to include in a research article so that everybody can use it. The first reporting guideline was created almost 30 years ago, and many more have been created since. The EQUATOR Network is the world's only global academic network dedicated to improving transparency in research reporting, primarily through the use of reporting guidelines. Most leading medical journals ask authors to adhere to reporting guidelines, yet adherence remains low in almost all medical fields. When authors do not adhere to reporting guidelines their work is less transparent, less valuable, contributes less to patient outcomes and has potential to inadvertently harm by distorting the evidence base. The aim of my thesis is to understand why authors do not adhere to reporting guidelines when writing up medical research, and to address these reasons with the intention of increasing adherence in the future. 

I began my thesis with this clear aim but without a route to get there. My first step was a qualitative synthesis (chapter {{< var chapters.synthesis >}}) of research exploring authors experiences of reporting guidelines, and I discovered authors' adherence to reporting guidelines is influenced by features of the guidelines themselves, but also the system that surrounds them including the websites that disseminate them and the people and policies of the broader scholarly ecosystem. I probed this system further with a review of quantitative surveys and an evaluation of the EQUATOR Network's website (chapters {{< var chapters.review & var.chapters.web-audit >}}). 

Given the complexity of the system and the complexity of the behaviour in question, I realised I would need a framework to help me make sense of them. I decided to use the Behaviour Change Wheel (chapter {{< var chapters.bcw >}}), a well established and evidenced framework for designing and defining complex behaviour change interventions. I led workshops and focus groups (chapters {{< var chapters.workshops >}} & {{< var chapters.focus-groups >}}) to guide stakeholders through frameworks' steps and, ultimately, ended up identifying {{< var counts.barriers >}} things that needed to change, and {{< var counts.sub_ideas_pre_jh >}} ideas of how to change them. These ideas were applicable to guideline developers, the EQUATOR Network, journals, publishers, funders, ethics committees, and institutions. 

I decided that redesigning reporting guidelines and EQUATOR's website would be an effective, affordable, acceptable, and equitable way to realise many of the generated ideas. I defined {{< var counts.ics.unique >}} intervention components and managed to incorporate {{< var counts.ics.included_unique >}} into a prototype website that included a redesigned reporting guideline (the Standards for Reporting Qualitative Research) and the EQUATOR Network's home page {{< var chapters.defining-content >}}. I then explored authors experiences of using this prototype through in-depth interviews, observation, think aloud, and writing appraisals {{< var chapters.pilot >}} and I identified {{< var counts.pilot.deficiencies >}} possible areas for improvement. 

My thesis' legacy is a website which could replace the EQUATOR's Network existing website and act as a dissemination platform to assist guideline developers who typically lack the money, time, and skills to create user friendly resources. By simply uploading plain text, guideline developers will be able to generate user-friendly and evidence-based resources, designed to increase adherence, with feedback channels baked in. I have secured funding for a feasibility study and parallel process evaluation to explore the acceptability and usability of the website amongst authors submitting to journals, in preparation for a future evaluation to determine whether my redesign leads to more authors adhering to reporting guidelines successfully. 
