bibliography: references.bib
csl: springer-vancouver.csl
filters:
  - docx-landscape.lua
project:
  title: "Thesis"
  output-dir: output
  execute-dir: project
  pre-render: create_variables.py
  preview:
    port: 4200
    browser: true
    watch-inputs: true
    navigate: true
execute:
  freeze: auto
format:
  html:
    toc: true
    theme: cosmo
    smooth-scroll: true
  docx:
      from: markdown+grid_tables
      reference-doc: reference.docx
      toc: true
      toc-depth: 2


