commitID: COMMITID
bibliography: references.bib
csl: springer-vancouver.csl
filters:
  - filters/docx-landscape.lua
  - filters/replace_todo.lua
crossref:
  sec-prefix: Chapter
project:
  title: "Thesis"
  type: book
  output-dir: output
  execute-dir: project
  preview:
    browser: true
    watch-inputs: true
format:
  # html:
  #   toc: true
  #   toc-depth: 4
  #   theme: [cosmo, theme.scss]
  #   smooth-scroll: true
  #   downloads: [docx, pdf]
  #   highlight-style: github
  #   include-in-header: metadata/noindex.html
  #   css: styles.css
  # docx:
  #     from: markdown+grid_tables
  #     reference-doc: reference.docx
  #     toc: true
  #     toc-depth: 2
  #     highlight-style: github
  quarto-thesis-pdf: 
      urlcolor: blue
      toclinkcolor: black
      toc-depth: 2
      fontsize: 12pt
      include-in-header: 
        text: |
            \usepackage{pdflscape}
            \newcommand{\blandscape}{\begin{landscape}}
            \newcommand{\elandscape}{\end{landscape}}
            \def\midrule{}
number-depth: 2

metadata-files:
  - metadata/_website.yml
  - metadata/_book.yml