commitID: COMMITID
bibliography: references.bib
csl: springer-vancouver.csl
filters:
  - filters/docx-landscape.lua
  - filters/replace_todo.lua
  # - filters/wordcount.lua
crossref:
  sec-prefix: Chapter
project:
  title: "Thesis"
  type: book
  output-dir: output
  execute-dir: project
  preview:
    browser: true
    watch-inputs: true
format:
  html:
    toc: true
    toc-depth: 4
    theme: [cosmo, theme.scss]
    smooth-scroll: true
    downloads: [docx] #, pdf]
    highlight-style: github
    include-in-header: metadata/noindex.html
  docx:
      from: markdown+grid_tables
      reference-doc: reference.docx
      toc: true
      toc-depth: 2
      highlight-style: github
  # pdf: 
  #     documentclass: scrbook
  #     pdf-engine: xelatex
  #     pdf-engine-opt: --xelatex
  #     latex-max-runs: 3
  #     keep-tex: false
  #     colorlinks: false
  #     papersize: a4
  #     linestretch: 1.5
  #     geometry:
  #         - inner=3cm
  #         - outer=4cm
  #         - top=3cm
  #         - bottom=4cm
  #         - headsep=22pt
  #         - headheight=11pt
  #         - footskip=33pt
  #         - ignorehead
  #         - ignorefoot
  #         - heightrounded
  #     toc: true
  #     toc-depth: 2
  #     number-sections: true 
  #     toc-title: Table of Contents
  #     fontsize: 12pt
  #     mainfont: "Times New Roman"
  #     sansfont: "Arial"
  #     monofont: "Courier New"
  #     include-in-header: include-in-header.tex
number-depth: 2

metadata-files:
 # - metadata/_footer.yml
  - metadata/_website.yml
  - metadata/_book.yml