bibliography: references.bib
csl: springer-vancouver.csl
filters:
  - docx-landscape.lua
project:
  title: "BCW-focus-groups"
  output-dir: output
  execute-dir: project
  preview:
    port: 4200
    browser: true
    watch-inputs: true
    navigate: true
format:
  html:
    toc: true
    theme: cosmo
    smooth-scroll: true
  docx:
      from: markdown+grid_tables
      reference-doc: reference.docx
      toc: false
      toc-depth: 2


