commitID: COMMITID
bibliography: references.bib
csl: springer-vancouver.csl
filters:
  - filters/docx-landscape.lua
  - filters/replace_todo.lua
  # - filters/wordcount.lua
crossref:
  sec-prefix: Chapter
project:
  title: "Thesis"
  type: book
  output-dir: output
  execute-dir: project
  preview:
    browser: true
    watch-inputs: true
format:
  html:
    toc: true
    toc-depth: 4
    theme: [cosmo, theme.scss]
    smooth-scroll: true
    downloads: [docx, pdf]
    highlight-style: github
    include-in-header: metadata/noindex.html
  docx:
      from: markdown+grid_tables
      reference-doc: reference.docx
      toc: true
      toc-depth: 2
      highlight-style: github
  pdf: 
      documentclass: scrbook
      pdf-engine: latexmk
      pdf-engine-opt: --xelatex
      latex-max-runs: 3
      keep-tex: false
      colorlinks: false
      geometry:
        - left=3cm
        - right=3cm
        - marginparwidth=1.5in
        - twoside=true
      toc: true
      toc-depth: 2
      number-sections: true 
      toc-title: Table of Contents
number-depth: 2

metadata-files:
 # - metadata/_footer.yml
  - metadata/_website.yml
  - metadata/_book.yml