commitID: COMMITID
bibliography: references.bib
csl: springer-vancouver.csl
filters:
  - filters/docx-landscape.lua
  - filters/replace_todo.lua
  # - filters/wordcount.lua
crossref:
  sec-prefix: Chapter
project:
  title: "Thesis"
  type: website
  output-dir: output
  execute-dir: project
  preview:
    browser: true
    watch-inputs: true
#format-links: [docx]
format:
  html:
    toc: true
    toc-depth: 4
    theme: cerulean
    smooth-scroll: true
    downloads: [docx]
    highlight-style: github
  docx:
      from: markdown+grid_tables
      reference-doc: reference.docx
      toc: false
      highlight-style: github
number-depth: 2

metadata-files:
  - metadata/_footer.yml
  - metadata/_website.yml
  - metadata/_book.yml