::: {.content-visible when-format="html"}

# Refining reporting guidelines dissemination using behaviour change theory {.unnumbered}

**James Harwood**

ORCID: 0000-0003-3530-3231

Doctor of Philosophy

January 2024

Nuffield Department of Orthopaedics, Rheumatology and Musculoskeletal Sciences

The University of Oxford

{{< pagebreak >}}

:::
<!-- content-visible -->

:::{.callout}
Here is the working version of my thesis. 

:::{.content-visible when-format="html"}
You'll find chapters on the left, and can download Word files for each chapter on the right. 

Chapters that I've not done (including this one) are [this colour]{.text-muted}. Chapters in [this colour]{.text-warning} are a works-in-progress. 
:::

If you see anything like "\@something", "**?:something**", or "#SOMETHING" then please ignore. 

Some of the tables and figures aren't rendering nicely yet, especially in Word format. You can ignore that too. 

:::{.content-visible when-format="docx"}
Known todos for DOCX output:

* Title page 
* Table and figure formatting
* Lists of tables & figures at start (necessary?)

:::

:::

::: {.content-visible when-format="html"}

## Word Count Tallies: 

Actual word counts will be lower as these numbers include tables, references, and appendices. 

{{< include metadata/_wordcounts.qmd >}}

:::