## Focus Groups - participant information {.appendix}

James Harwood

DPhil Candidate in Musculoskeletal Sciences

Nuffield Department of Orthopaedics, Rheumatology and Musculoskeletal Sciences

Botnar Research Centre, University of Oxford

University email: james.harwood\@stx.ox.ac.uk

#### Improving the dissemination of reporting guidance using behaviour change theory: focus groups with guideline developers and editors

**Participant information sheet**

Central University Research Ethics Committee Approval Reference: R80414/RE001

#### What is the purpose of this study?

Reporting guidance is disseminated through a system that includes the guidelines themselves, websites (e.g., journal instructions, the EQUATOR Network website), tools (e.g., checklists), and other people (e.g., editors, reviewers). The aim of this study is to identify barriers in any part of this system that may stop authors from successfully using reporting guidelines and possible ways to overcome those barriers.

#### Who is conducting the study?

Focus groups will be led by the project lead, James Harwood, a DPhil student at the UK EQUATOR Centre supported by a grant from Cancer Research UK supervised by Professor Gary Collins (Professor of Medical Statistics, University of Oxford.

#### Why are we approaching you?

We are inviting individuals who have insight into how reporting guidance is disseminated. The current dissemination system includes resources created and maintained by different groups: developers of reporting guideline and advocates, publishers, and the EQUATOR Network.

#### What will happen to me if I take part?

**Pre meeting activity:** We will ask you to think about facilitators and barriers that may affect whether authors use reporting guidance successfully, and to make note of these in a shared online document. All members of your group will access and edit the same file.

**Online focus group:** The focus group will last 2 hours. We will begin by discussing the facilitators and barriers that your group members identified before the focus group. We will then compare these with the facilitators and barriers identified by previous participants. You will then be asked to come up with ways to address these facilitators and barriers, before considering the thoughts of previous participants.

You will be asked to collaboratively edit an online document. Each focus group will build upon the output of the previous focus groups. Your writing will be anonymous but will be viewable to other participants.

If you would like more time you will have the option of extending the focus group or arranging a second date.

**After the focus group:** You will receive a copy of the document produced in your focus group and invited to add comments to it should you have any thoughts after the focus group ends. When all focus groups have taken place, you will be sent a copy of the final document and invited to give feedback on it.

#### Do I have to take part?

Participation is completely voluntary. If you change your mind about participating, you can withdraw at any point by letting the project lead know ([james.harwood\@stx.ox.ac.uk](mailto:james.harwood@stx.ox.ac.uk)) including during the focus group. If you choose to leave we will retain any research data that you have contributed. 

#### How will my data be used?

We will collect your name and email so that we can share the outputs of your focus group and of the study and invite you to comment on them. We will record the audio of the focus group so that the lead researcher can refer to it if needed to avoid recall bias. Your thoughts about barriers and solutions will influence subsequent research projects.

#### Who will have access to the files co-produced in my focus group?

At the end of your focus group we will share a copy of the file to all participants in that focus group. We will remove all tracked changes, comments, or other identifiable information before sharing it. Once all focus groups have been held, we will share a version of the final, de-identified output.

#### What happens to the data provided?

The information we acquire during the study is the research data.  Any research data from which you can be identified, such as your contact details, consent record and audio recording, is known as personal data. All data will be stored on secure, backed-up servers at the Nuffield Department of Orthopaedics, Rheumatology and Musculoskeletal Sciences, University of Oxford and will be held by and accessible to the research team. Audio recordings and contact details will be deleted immediately after the results are written up and the data is no longer needed. Other research data (including consent records) will be stored for at least 3 years after publication or public release of the work of the research. Responsible members of the University of Oxford may be given access to data for monitoring and/or audit of the research.

We would like your permission to use short excerpts from your focus group, against a pseudonym, in our publications and research presentations. All personal information that could identify you will be removed or changed before doing so.

#### Will the research be published?

The research may be published in a student thesis, academic publications and on the EQUATOR Network site and shared in academic presentations in venues such as conferences. A copy of my thesis will be deposited both in print and online in the [Oxford University Research Archive](https://www.bodleian.ox.ac.uk/finding-resources/theses/theses) where it will be publicly available to facilitate its use in future research.

#### Who is funding the research?

This research is funded by Cancer Research UK.

#### Who has reviewed this study?

This study has been reviewed by, and received ethics clearance through, a subcommittee of the University of Oxford Central University Research Ethics Committee (R80414/RE001).

#### Who do I contact if I have a concern about the study or if I wish to complain?

If you have a concern about any aspect of this study, please contact James Harwood (james.harwood\@stx.ox.ac.uk) and I will do my best to answer your query. I will acknowledge your concern within 10 working days and give you an indication of how it will be dealt with. If you remain unhappy or wish to make a formal complaint, please contact the Chair of the Medical Sciences Interdivisional Research Ethics Committee at the University of Oxford who will seek to resolve the matter as soon as possible. Email: ethics\@medsci.ox.ac.uk; Address: Research Services, University of Oxford, Boundary Brook House, Churchill Drive, Headington, Oxford OX3 7GB.

#### Data Protection

The University of Oxford is the data controller with respect to your personal data, and as such will determine how your personal data is used in the study.

The University will process your personal data for the purpose of the research outlined above.  Research is a task that is performed in the public interest.

Further information about your rights with respect to your personal data is available from <https://compliance.admin.ox.ac.uk/individual-rights>.

#### Further Information and Contact Details

If you would like to discuss the research with someone beforehand (or if you have questions afterwards), please contact:

James Harwood

DPhil Candidate in Musculoskeletal Sciences

Nuffield Department of Orthopaedics, Rheumatology and Musculoskeletal Sciences, Botnar Research Centre, University of Oxford

University email: james.harwood\@stx.ox.ac.uk