
# Introduction

::: {.SRQR data="Item 3. Problem Formulation: Description and significance of the problem/phenomenon studied; review of relevant theory and empirical work; problem statement."}

In chapter {{< var chapters.bcw >}} I described the Behaviour Change Wheel (BCW) framework for designing behavioural interventions @michieBehaviourChangeWheel2011 and I summarised the stages recommended in Michie et al.'s accompanying book @michieBehaviourChangeWheel2014 for using the framework to develop interventions. I also described the additions that I made to this approach. I described the first of these additions in chapter {{< var chapters.workshops-ideas >}}, where I explained why I decided to ask EQUATOR members to brainstorm ideas to address barriers by considering intervention functions in turn. This chapter describes how I extend this list of {{< var counts.EQUATOR_ideas >}} ideas by seeking input from the broader reporting guideline community into this ideation phase.

I did this because, although EQUATOR staff have a lot of experience in reporting guidelines (which I describe in chapter {{< var chapters.workshops >}}), the group is small, close-knit, and homogenous in many ways. Most members have worked for EQUATOR for many years. All live in the UK and work for Oxford University. All are passionate about transparent reporting and come from a quantitative research background. Hence the group's experience and opinions may not represent people from other countries, disciplines, industries, or guideline developers not affiliated with EQUATOR.

This is important because whilst EQUATOR is a key part of the reporting guideline landscape, they are _only_ a part of it. Ultimately, all stakeholders within the academic system influence the impact of reporting guidelines. Guideline developers and publishers arguably do so most directly currently, and so it was important to draw on their experience and opinions. It wasn't feasible to include these stakeholders through all stages of the BCW approach as a) the time commitment was too great, b) it would have required stakeholders to become familiar with the framework and its terminologies which was too big an ask and c) options that may be feasible to a publisher might not be for EQUATOR (I talk about this more in chapter {{ var chapters.workshop-stage-5-6 }}). 

In contrast, adding an idea-generating step provided a good opportunity to include stakeholders. Stakeholders could provide their own ideas and share their perspective on EQUATOR's ideas, in a short amount of time and without having to study the Behaviour Change Wheel. In this chapter, I describe how I ran focus groups to gather ideas from guideline developers, publishers, and other experts.

<!-- # ASK Charlotte: is the objective clear, justified, and sign posted? -->
<!-- Although some EQUATOR members have developed reporting guidelines, their experience may not be representative of "external" guideline developers who, despite having a deep understanding of their own guidance, may consider reporting guidelines as a small part of their academic identity and may not "live and breathe" reporting guidelines in the same way EQUATOR does. -->
:::




