## An organic, complex intervention

The birth of reporting guidelines was a slow, grass-roots process, driven by lots of groups of people doing what they felt was sensible. This movement generated guidance publications, checklists, websites, and training materials. 

The publishing community began to take note. The International Committee for Medical Journal Editors encourage journals "to ask authors to follow [reporting] guidelines" @ICMJERecommendationsPreparing. Concerned editors sought ways to adopt reporting guidelines, and more and more journals (#REF) have since found a range of strategies to introduce reporting guidelines into their policies, outlined in @tbl-journal-policies. There is variation in the degree of enforcement (from passive recommendation through to compulsory enforcement) and variation in which guidelines are subject to the policy; PRISMA and CONSORT and more commonly enforced than STROBE, say, and many of the 500+ reporting guidelines in EQUATOR's library are not enforced nor endorsed by any journals. Instead of listing reporting guidelines by name, many journals keep their instructions vague and merely recommend authors find an appropriate guideline on EQUATOR's website.

{{< include _table_policies.qmd >}}

Other stakeholders have begun incorporating reporting guidelines into their policies. Conferences like the Peer Review Congress ask applicants to use reporting guidelines when writing their abstracts. MedRxiv, a large preprint server, asks authors to declare they have "followed all appropriate research reporting guidelines, such as any relevant EQUATOR Network research reporting checklist(s)" @MedRxivOrgPreprint. 

EQUATOR have developed training programmes based on reporting guidelines. The training covers different ways to use reporting guidelines, including drafting manuscripts, checking manuscripts you have written, and appraising the reporting of someone else's manuscript. 

Hence over the years, a system has organically grown around reporting guidelines. This system includes the guidance resources themselves (the publications, checklists, flow diagrams), the websites that host those resources (guideline websites, the EQUATOR website, publisher's websites), organisations that promote or enforse their use (EQUATOR, publishers, ICMJE), and staff at those institutions (researchers, editors, reviewers). Together, these parts seek to influence what authors report. 

This system meets the Medical Research Council’s (MRC) definition of a complex intervention: "an intervention might be considered complex because of properties of the intervention itself, such as the number of components involved; the range of behaviours targeted; expertise and skills required by those delivering and receiving the intervention; the number of groups, settings, or levels targeted; or the permitted level of flexibility of the intervention or its components." Reporting guidelines and the system that surrounds them meet these criteria, as described in @tbl-mrc-criteria. 

#TODO turn criteria into a table

Each guideline has many potential components (a guidance document, checklist, website, training). These components are disseminated through various channels (journal author guideline pages, submission systems, the EQUATOR website e.t.c.). Guidelines comprise "reporting items". Some items are relatively simple, like asking the author to specify their study deisgn in the title. But other items are harder, in that they require the author to complete other actions when designing a study or collecting data. Hence guidelines target a range of behaviours. Reporting guidelines are written by academics for their peers, and so authors, editors, and reviewers must have sufficient expertise to use them. Users of reporting guidelines differ in experience, place of work, proficiency with english or with writing, and they use guidelines for different tasks - drafting, checking, appraising. These tasks occur in different contexts and are performed by different people. 

The MRC acknowledges "Flexibility in intervention delivery and adherence might be permitted to allow for variation in how, where, and by whom interventions are delivered and received". This flexibility manifests as differences between guideline content, resources, and differences between implementation strategies. 

The MRC recommends that "complex interventions can helpfully be considered as events in systems". In this thesis I take a systems view of reporting guidelines. At first glance this may seem novel. In "A history of the EQUATOR Network", Doug Altman refers to reporting guidelines as "resources" that "influence" reporting, but he does not call them interventions. Other studies call reporting guidelines "tools" or "strategies" (#REF). 

However, I would argue that most previous research exploring the efficacy of reporting guidelines has also taken a systems perspective, even if this is not explicit. Because reporting guidelines do not exist in a vaccum, it is difficult to separate the guidelines themselves from the policies, people, websites, and tools involved in their implementation. Hence, studies that ask "have reporting guidelines had an effect?", are actually exploring the efficacy of the _system_ that has grown on top of reporting guidelines; a system that has grown organically and continues to change. I explore these studies in the next section. 