## Thesis structure

**Chapter {{< var chapters.reflexivity >}} - {{< var titles.reflexivity >}}**

I reflect on my background, my prior held opinions, and those of my supervision team, and how these may have influenced the direction of this thesis. 

**Chapter {{< var chapters.synthesis >}} - {{< var titles.synthesis >}}**

The next three chapters pertain to my first objective - to identify possible reasons as to why reporting guidelines have had only a limited impact on reporting quality. This chapter describes a thematic synthesis of studies that qualitatively explored authors' experiences of using reporting guidelines, where I sought to identify what may influence whether an author successfully adheres to reporting guidance. 

**Chapter {{< var chapters.review >}} - {{< var titles.survey_content >}}**

This chapter builds on the previous one by identifying additional possible influences from the content of quantitative survey questions. 

**Chapter {{< var chapters.web-audit >}} - {{< var titles.website_audit >}}**

This chapter describes the characteristics and behaviour of visitors to the EQUATOR Network website. This website, although an important piece of the reporting guideline infrastructure, was rarely explored by studies reviewed in the previous two chapters. This evaluation adds further context to barriers identified in the previous chapters, and goes on to inform discussions and decisions in later chapters. 

**Chapter {{< var chapters.bcw >}} - {{< var titles.bcw >}}**

The next 3 chapters pertain to my second objective - identifying intervention changes. This chapter introduces the Behaviour Change Wheel, which is a framework for designing and defining behaviour change interventions. I explain how my thesis gained form at this point in time; my view of reporting guidelines as a system crystallised, and Charlotte Albury joined my supervision team as my plans took an unexpected qualitative turn. I wanted my thesis to accurately reflect the twists and turns of my DPhil, and so instead of introducing my chosen framework at start of my thesis (which may customary), I introduce it in the middle to more accurately reflect my journey.

**Chapter {{< var chapters.workshops >}} - {{< var titles.workshops >}}**

This chapter describes how I lead workshops with reporting guideline experts from the UK EQUATOR center to identify intervention options using Behaviour Change Wheel framework.

**Chapter {{< var chapters.focus-groups >}} - {{< var titles.focus_groups >}}**

This chapter reports focus groups where I collected ideas on how intervention options could be realised. 

**Chapter {{< var chapters.defining-content >}} - {{< var titles.defining_content >}}**

In this chapter, I bring together the outputs of the previous two chapters to create a table of intervention components. I then describe how I implemented these components by redesigning a reporting guideline (SRQR) and the EQUATOR Network website's home page.

**Chapter {{< var chapters.pilot >}} - {{< var titles.pilot >}}**

In this chapter I address my final objective by refining the intervention in response to feedback from authors. I describe a qualitative study where I used observation, think aloud, structured interviews, and a writing evaluation, to gather feedback from an international sample of authors. 

**Chapter {{< var chapters.discussion >}} - {{< var titles.discussion >}}**

After summarising my findings and outputs, I reflect on the strengths and limitations of my approach, next steps, and the impact I hope my work will have on the scholarly publishing, the meta-research community, and implications for policy.
