## Introduction

In this chapter I describe how I brought together the outputs of all previous research chapters to create an intervention planning table containing intervention components. I then describe how I turned this table into a working prototype ready to be tested by authors.

In chapters {{< var chapters.synthesis >}} - {{< var chapters.web-audit >}} I described how I identified barriers influencing whether authors adhere to reporting guidelines. In chapter {{< var chapters.workshops >}} I described how ran workshops with reporting guideline experts at the UK EQUATOR Centre to define a target behaviour, prioritise intervention functions and policy categories, and how we decided to prioritise redesigning reporting guidelines and the EQUATOR Network's website hope page. In chapter {{< var chapters.focus-groups >}} I described how I asked guideline developers, publishers, and other stakeholders to build upon our workshop outputs by brainstorming solutions to barriers. 

Consequently, at this point in my thesis I had multiple lists; a list of barriers, lists of intervention options, and a list of ideas. Not all ideas were relevant to the EQUATOR Network or aligned with our prioritised intervention options, and although ideas referenced barriers, the links between ideas, barriers, intervention functions, and behaviour change techniques were not fully explicit. 

What remained was to select ideas I could implement, define them as intervention components, then build a prototype I could test with authors. Michie et al.  @michieBehaviourChangeWheel2014 define an intervention component as:

1. a designed element that uses one or more behaviour change technique,
2. theorized to work through one or more intervention functions 
3. to target one or more behavioural drivers. 

Michie et al. @michieBehaviourChangeWheel2014 describe this step as "identify[ing] intervention content in terms of which [behaviour change techniques] best serve intervention functions", where a behaviour change technique is "an active component" that is "observable, replicable, [and] irreducible". Defining intervention content in this way is useful because it helps intervention developers understand why the component was added (or removed), how it is theorised to work, and how its effectiveness may be tested.

Once defined, I wanted to turn this list of intervention components into a prototype that could be tested by authors. This prototype would have to include a) a redesigned reporting guideline and b) a redesigned version of the EQUATOR Network home page that testers could navigate to find the redesigned reporting guideline. I wanted the prototype to be real enough so testers could use it as they would a real website. This meant I had to make decisions about content, design, and also the underlying software used to create and host the website.

I wanted to include EQUATOR staff and guideline developers in the redesign process for three reasons. Firstly, because EQUATOR staff will need to take responsibility of what I build if it is to be successful, the underlying architecture must be easy for them to understand and maintain and affordable to run without funding. Secondly, I expected their experience and expertise to help decision making and by prioritising their opinions I hoped to keep my own subjectivity in check. Thirdly, I wanted to ensure they understood the intervention and felt like it was "ours" not "mine".

I did not have time to consult multiple guideline groups. Nor did I have time to redesign multiple guidelines. For the purpose of building a prototype I decided to focus on a single reporting guideline; the Standards for Reporting Qualitative Research (SRQR). I chose this guideline because I was familiar with it, understood it, and it's lead developer expressed interest in collaborating. Additionally, because it is applicable to all medical qualitative research I expected its users to be plentiful and varied. For example, authors may include students, clinicians, public health experts, quantitative researchers dabbling in qualitative methods within a positivist framework, or experienced qualitative researchers working within other paradigms. This broad and varied author base would be useful for a subsequent qualitative feedback study (see next chapter).

In summary, the aim of this chapter was to create an intervention in preparation for a subsequent qualitative user feedback study. My objectives were to:

1. Create a list of intervention components by combining the outputs of previous chapters
2. Redesign the EQUATOR Network home page and SRQR guideline 
