### Discussion

The aims of this chapter were to create an intervention component table by drawing on the results of all previous chapters, and to turn these components into a prototype ready to test amongst authors. The intervention component table brings together the outputs of all of my previous thesis chapters and links them together; each component comes from an idea (chapter {{< var chapters.focus-groups >}}), and addresses one or more barriers (chapters {{< var chapters.synthesis >}} - {{< var chapters.web-audit >}}) using intervention options ranked favourably by EQUATOR staff (chapter {{< var chapters.workshops >}}). My design process relied on this table and I used it again in my next chapter as an analysis framework. Hence this table, although relegated to the appendix because of its size, is a focal point for my thesis: it crystallises all preceding chapters, and formed the basis for all of my subsequent work.

The table includes components derived from all ideas pursuant to the intervention options EQUATOR staff and I prioritised in our workshops. Because I filtered out ideas _not_ in line with our priorities, the list is not exhaustive. Stakeholders using the same set of initial ideas would create different components because of their different priorities and implementation opportunities. For example, a funder may have generated more components related to reporting guidance for applications or protocols, or relating to their application criteria and submission systems. Stakeholders with the power to grant approval (for funding/ethics/publication) may have components related to enforcement or reward. Consequently, although I hope my list will help readers understand the intervention changes I have made and why I have made them, I would encourage other intervention designers to go through this process themselves instead of using this list verbatim.

Throughout the intervention component table I have drawn comparisons between the proposed components and existing reality. Sometimes these comparisons are vague; I use terms like "some" or "rarely". Where possible, I refer to images or examples. Some examples came from my qualitative synthesis (chapter {{< var chapters.synthesis >}}), others arose organically in my workshops (chapter {{< var chapters.workshops >}}) when participants shared long-standing frustrations with reporting guidelines or EQUATOR's website. Other times, after discussing a barrier or idea, we would look at a few guidelines to see how things are done currently. So my comparisons were ad-hoc, and I have included them only to provide context to the proposed changes. I considered making this comparison formal by systematically coding BCTs employed by EQUATOR's website and popular guidelines. Ultimately, I decided this would not be helpful nor practical. With so many components and so many guidelines, this would have taken too long and I decided instead to prioritise building and testing a prototype. Secondly, I doubted this audit would influence my subsequent design, but would merely quantify how my redesigned intervention differs to the current set-up. Should a quantifiable comparison be useful, it would be more appropriate to do it after the redesigned intervention has been refined in response to user feedback, once its design is stabilised.

Using this intervention component table I have created functional prototypes of a redesigned reporting guidelines and the EQUATOR Network home page. These new designs include {{< var counts.redesign.intervention-components.included_unique  >}} of the {{< var counts.redesign.intervention-components.unique >}} intervention components I identified. 

Using a framework and a systematic method helped the design advisory panel and I to make decisions based on evidence and theory, and to reduce the influence of our own subjectivity. Instead of relying on personal preference, we tried to ensure choices reflected the function we were trying to employ. For example, when choosing a background image, instead of asking "do you like this one?", the questions became "what feelings do you think this image conveys? Does it communicate simplicity?". this reflection was also useful when exploring disagreements between panel members. For example, when sketching layouts for the home page, some panel members drew a single, prominent search button. Others drew a plethora of options like "view guidelines by speciality", "view guidelines A-Z". Discussion revealed that whereas some staff prefer to search directly for what they want with laser-like focus, others prefer to explore, especially when they are not certain what they want or what the website is about. In this instance, the final design takes both use cases into account, but other times we resolved disagreement by referring to the intervention planning table or to similar websites. Hence using a framework and exploring disagreements as a group helped mitigate personal preferences. 

However, many decisions required a degree of subjectivity and, as lead researcher, designer, and developer, often these decisions landed on my shoulders. I tried to mitigate this by prioritizing other people's ideas over my own, and providing many opportunities for feedback. But the result undeniably has my “stamp”. If someone else had built it using the same table of intervention components then some things might be the same (like simplifying the user journey from 5 steps to 2, or the conventional home page layout and search button position) but other things would look different (like the choice of wording and images).

My design may have benefited from input from other stakeholders. I describe how I obtained feedback from authors in my next chapter, but I would have liked to include authors, publishers, funders, and other stakeholders from the start of the design process. If EQUATOR decide to take my designs forward, these consultations could still take place, but they were not feasible within the time constraints of my PhD. 

Input from user experience experts and graphic designers would also be useful. We found images to be a time consuming pain point. None of us had the skills to create professional looking graphics ourselves, and we found most free stock images were generic and did not communicate what we needed. 

My experience of working with SRQR's lead developer, Bridget, was was positive; she was supportive, liked the result, and she was interested when my process revealed gaps in SRQR item description. For example, often there was no guidance of what to write if a reporting item was not or could not be done. Some items did not explain why they are important and to whom. Filling these blanks required time and input that SRQR's development team were unable to give at present, and so I left these gaps unfilled for now. I anticipate other guidelines will have similar gaps. I hope other guideline developers will be as open-minded as Bridget was, but I expect others may feel less able or motivated to engage with a redesign, or may feel protective over their writing and resistant to change. 

In addition to filling these gaps, making my redesign "live" would require further technical work. Some of these tasks are administrative and have no behaviour change impact, but there are still {{< var counts.redesign.intervention-components.not_included_unique >}} intervention components outstanding. These components were too difficult or time consuming to include at this stage. For example, I intended to include more examples of reporting items, including examples of concise reporting or transparently reported "imperfect" items. EQUATOR could add these intervention components at a later date. Other components may require significant design and development work, most notably creating ready-to-use checklists and templates. 

If EQUATOR chooses to adopt these changes and apply them to other guidelines, hundreds of thousands of authors would access these redesigned resources each year. These redesigned resources have potential to benefit authors directly, and also to help other stakeholders. For example, publishers may find enforcing guidelines easier if our redesigned resources prove more user friendly. Guideline developers will benefit from having a ready-to-use dissemination platform based on evidence, with built-in channels for collecting feedback from authors. This feedback may help guideline developers refine their resources further, and could act as evidence to support future funding applications. 

## Conclusions

By linking components with barriers, functions, and behaviour change techniques, I have justified components using evidence and described how they are theorized to work. This table will help other intervention developers and stakeholders understand what changes I have made and why. It also helped me redesign the EQUATOR Network's home page and the SRQR guideline. These new designs include {{< var counts.redesign.intervention-components.included_unique >}} of the {{< var counts.redesign.intervention-components.unique >}} intervention components I identified, and many of the remainder could be added later. Although my designs may have benefited from including other stakeholders, I explained how I facilitated open discussion, prioritised other's opinions, and used my intervention component table to make decisions. In the next chapter I explain how I refined these designs further by interviewing and observing authors.

### Reflections on reporting this chapter

This was the hardest chapter to write. Initially I included it in my focus groups chapter, then I split it apart, and had separate chapters for defining intervention components and developing the intervention which I subsequently rejoined. I found it difficult because it did not obviously fit into a traditional research package. I had objectives, but no research questions. I had an approach and outcomes, but they didn't feel like methods and results and when my approach was iterative it felt difficult to force it into a linear narrative. There were no reporting guidelines to help me and so instead I turned to the internet to seek general advice for structuring and writing academic text. I landed on Rachael Cayley's blog, _Explorations of Style_ @ExplorationsStyle and Helen Sword's book _Stylish Academic Writing_ @swordStylishAcademicWriting2012. In particular, I found Rachaels' description of _Reverse Outlines_ as a technique for unpicking and restructuring messy text useful for revising this chapter. Reading these made me realise how little I knew about writing as an art and as a skill. When writing my early chapters I tried using a reporting guideline as a skeleton and I then filled in the blanks. I made no outlines, no structural scaffold beyond the guideline. Because I had no reporting guideline for this chapter I had lost my crutch, and my inexperience in structuring writing became apparent. I've never enjoyed it but I had always thought I it was skill I had ticked and would never forget. But reading Rachael's blog and Helen's book made me realise how little I knew and how much I had forgotten since my only formal writing training in GCSE English 20 years ago! I'd forgotten the nuts and bolts of structuring arguments, paragraphs, or sentences. I'd forgotten the heuristics of clear writing, and developed an unhealthy reliance on passive verbs and relative clauses. 

This realisation was interesting to me as it revealed barriers beyond reporting guidelines. If readers cannot understand my work it's probably not _just_ because I failed to adhere to a reporting guideline, but also because I'm an inexperienced writer and my writing is often clunky and imprecise. When workshop members talked about educating authors about writing as a skill (chapter {{< var chapters.workshops >}}) the idea did not resonate with me until now, and I realise that the website I've created contains little advice about writing in general. If I had reflected on my own struggles with writing before making the website, perhaps I would have tried harder to address this problem in the redesign. That I am already reconsidering design choices points to two further realisations. Firstly, it's a reminder of the subjectivity that is inevitably part of any design process, despite my efforts to remain systematic and objective. Secondly, it reveals my hope that the website will be improved in response to evolving needs, context, evidence, and understanding, ideally derived from user feedback, which is the subject of my next chapter. 
