
## Methods

### Defining intervention components

I started with a list of {{< var counts.ideas >}} ideas. These were the 128 ungrouped ideas originating from my focus groups (chapter {{< var chapters.focus-groups >}}), plus {{< var counts.sub_ideas >}} ideas I had whilst I was writing my focus group chapter (see Appendix {{< var appendices.ideas >}}).

I labelled each idea with:

1.  The barrier(s) it addresses (derived from chapters {{< var chapters.synthesis >}}, {{< var chapters.review >}}, {{< var chapters.web-audit >}}, and {{< var chapters.workshops >}}).
2. The behavioural driver it targets (from step four of the workshops described in chapter {{< var chapters.workshops >}}).
3. The intervention functions it uses.
4. The behaviour change techniques it uses, selected from Michie et al.'s taxonomy @michieBehaviorChangeTechnique2013.

I asked a colleague with experience in behaviour change taxonomies to double check my coding, and we resolved disagreements through discussion.

For each idea, I then considered:

5. Whether it was implementable by redesigning guidelines or by modifying the EQUATOR website. If not, I removed it from the list.
6. Whether its intervention function aligned with the intervention options EQUATOR and I had prioritised during our workshops (see workshop steps 5 & 6 in chapter {{< var chapters.workshops >}}). If not, I removed it from the list.

To give structure to this list, I grouped intervention components according to the sub-behaviours they targeted: 1) engaging with guidance and 2) applying it (see section on specifying the target behaviour in chapter {{< var chapters.workshops >}}).

To provide extra context and clarity, I described each component in more detail and how it compares to the status quo. In doing these comparisons I made generalisations about how popular reporting guidelines are written and disseminated by drawing on evidence from my qualitative synthesis ({{< var chapters.synthesis >}}), looking at how the EQUATOR website is currently, referring back to workshop discussions (from chapter {{< var chapters.workshops >}}).

### Redesigning the SRQR reporting guideline and EQUATOR Network home page

#### Design meetings and process

I invited the EQUATOR staff who participated in the workshops (chapter {{< var chapters.workshops >}}) to attend three design meetings between November 2022 and January 2023. In our first meeting, we decided how the home page and redesigned guideline should join and whether any interim steps were required.

In our second meeting, EQUATOR staff and I sketched ideas for how the home page and reporting guideline page could be laid out and for the positioning of intervention components. These sketches were wireframes: simple illustrations focussing on space allocation, functionalities, and intended behaviours. Wireframes do not include styling. There are no colours, images are represented as blank boxes, and squiggles represent blocks of text. 

After the second meeting, once participants had agreed on a layout, I created an alpha version of the new home page and guideline page. These were real webpages, viewable in a browser, but I used dummy text and images because I wanted to solicit feedback on layout, structure, and functionality, not on the content. This is a common practice in web development, as people can become distracted by wording or stylistic choices. I used a web annotation tool called Pastel to collect feedback from EQUATOR staff @PastelFastestVisual and then refined the alpha version based on this feedback.

In our third meeting, we co-created text for the home page. We began by listing the intervention components the text needed to address. The text needed to explain what reporting guidelines were, how they can be used, and the benefits they bring to authors. EQUATOR staff drafted text on their own before discussing and editing as a group. We also discussed style and imagery in this meeting. Again, we began by listing the intervention components the images needed to address. These included communicating what reporting guidelines are, who should use them, communicating simplicity and confidence. I invited EQUATOR staff to contribute websites and images they admired for inspiration. We ended up discussing websites run by the National Health Service @NHSWebsite2018, the International Organisation for Standardisation @ISOInternationalOrganization2023, and the National Institute for Health and Care Excellence @NICENationalInstitute. We looked through examples of free-to-use images from a number of libraries @8guildSearchDownloadFree; @DownloadFreeVectors; @FreeIconsStickers; @FreepikDownloadFree. I also consulted usability best-practices @experienceNielsenNormanGroup. I then populated the alpha version with the text and images discussed in this meeting.

After the third meeting I began redesigning the SRQR guideline. I got written permission from SRQR's publisher and lead developer, Bridget O'Brien. I began redesigning SRQR by pasting the text into Microsoft Word and rearranging content into categories: what to write, how/where to write it, what to write if the item was not/could not be done, why the item is important and to whom, and examples. I edited sentences to speak directly to authors and to use active voice. E.g. "Describe X" instead of "X should be described". This shortened the text and made it clearer that the primary audience is authors.

For composite items I split the sub-items into bulleted lists. E.g.

> For each X, describe:
>
> * A
> * B
> * C
>

I rearranged conditional sub-items to read as "If X, then describe Y", instead of "Describe Y if X". I moved definitions into a glossary and contextual information into notes. I edited the tone of voice to add reassuring language. An example redesigned SRQR item is in #sec-box-item. I asked SRQR's developer to provide feedback on the redesigned guideline and made refinements based on her comments.

After development, I double checked the intervention against my intervention planning table (see chapter {{< var chapters.defining-content >}}) to ensure I had included all components. I invited another round of feedback from EQUATOR staff and made more refinements.

#### Trustworthiness

As before, I used established, best-practice techniques to facilitate open discussion @lincolnNaturalisticInquiry1985. I made it clear there were no right or wrong answers. I reflected on my own opinions before meeting, and held them back until EQUATOR staff had finished talking. When disagreements arose, I took time to explore and understand both sides. 

I made heavy use of my intervention planning table (see chapter {{< var chapters.defining-content >}}) to make decisions based on theory over and above personal preferences. Instead of asking EQUATOR members whether they liked something (e.g., _Do you like this font?_), I asked whether they felt it reflected the intended intervention function instead (e.g., _Does the font convey simplicity?_). By prioritising theory above preference and others' opinions above my own, I reduced my subjectivity.

#### Target audience 

Throughout our meetings we kept our target audience in mind. Building user personas is a common best practice in web development @ISO92412102019 @velsenPersonasLinkingPin2012 @experiencePersonasMakeUsers. For example, as part of their work to help NHS staff adopt new technologies and become a digital workforce, Health Education England identified archetypes: digital creators, end users, embedders, change drivers, and shapers @PersonasHealthEducation. They then developed imaginary personas around these archetypes, each with their own needs, motivations, and challenges. Developing personas can be a significant task. Some product teams go as far as interviewing 5 or more representatives of each persona in an iterative, co-creation process. This was not feasible within my PhD and so my persona generation process was less formal but still evidence based. Referring to my website service evaluation (chapter {{< var chapters.web-audit >}}), I recalled most website visitors are new and visit only once, and so I assumed many will be naïve to reporting guidelines and the EQUATOR Network. Website visitors come from all over the world, so I assumed some may speak english as a second language (or not at all). I had no way of knowing how much research experience EQUATOR's website visitors have, but I assumed the distribution would reflect real-world numbers, where students and early career researchers outnumber experienced professors. Although the EQUATOR website has content aimed at editors, librarians, and guideline developers, this content is rarely accessed and these users are not part of my target behaviour (see chapter {{< var chapters.workshops >}}), and so I did not create personas for them. 

Consequently, two personas crystallised in my mind: inexperienced and experienced authors. 

1. Inexperienced author:

* may not be familiar with EQUATOR or reporting guidelines
* may find authoring / publishing difficult
* may need help in finding, understanding, and applying a reporting guideline
* if English is their second language, they may be less proficient in reading/writing in it

2. Experienced author:

* may be familiar with EQUATOR and/or reporting guidelines
* may have used checklists before, but may not realise full guidance exists, and may have never used reporting guidelines for for drafting.
* may feel patronized or restricted by reporting guidelines, especially if they believe them to be design requirements
* may see checklists as red tape necessary for publication, or they may be reporting guideline "converts" already convinced of their value.

Many authors may fall somewhere between these two personas. In discussion with EQUATOR staff, I decided to prioritise inexperienced authors because I believed them to be more numerous, and because qualitative evidence suggests inexperienced authors may benefit more from reporting guidelines but experience more barriers when using them (see chapter {{< var chapters.synthesis >}}). By focussing on helping inexperienced authors, I hoped any spill-over effects may also help experienced authors. 

User personas typically include motivations. There is an important difference between user motivations - what authors are wanting to do when they visit EQUATOR's website - and our target behaviour - what _we_ want authors to do when they visit EQUATOR's website. Because most visitors come from journal websites or submission systems and because checklists are the most accessed resourced (chapter {{< var chapters.web-audit >}}), we assumed most authors visit the website because they want to fill out a reporting checklist as part of journal submission. In contrast, we want authors to read the full reporting guidelines _as early as possible_, i.e. when planning or drafting research, way before they submit to a journal. We could have designed a website to focus entirely on drafting manuscripts, but this would have abandoned authors seeking checklists. Instead, we took a more pragmatic approach and decided to continue catering for authors seeking checklists, but to nudge them towards using the full guidance for drafting research in the future.

#### Making decisions about system architecture

When considering architecture options I spoke to staff members about financial constraints, data security concerns, and to understand what website builders and technologies they felt comfortable with. I then looked at the designs we had created on paper, considered the functionality those designs would require, and selected architecture options to support those  functions.