
# Behaviour Change (Target: 1000)

In my introductory chapter I presented how I view reporting guidelines to be part of a _complex behaviour change intervention_. But that isn't how I have always viewed them. In fact, when I began my PhD I had never heard of the term. But after reading accounts of authors struggling with the guidance content, access, formats, workflows, confidence, and the behaviour of others, I began to think less of the guidance text, and more about the system.

I started looking for a framework that could help me work out how this system could be changed to address the barriers I identified. Initially, and probably because of my background in software development, I looked at user experience literature (e.g., @experienceGuideUsingUserExperience) but quickly realised that heuristics for creating easy-to-use websites don't really generalise to long-form instructional text. Thinking of comparable documents, I then looked into user testing instruction manuals (@DevelopmentUsabilityTesting; @mollerUsabilityTestingUser2013) but found that focusing on the document alone neglected other parts of the intervention, like the impact of journal policies or the behaviour of peer reviewers. A conversation with a professor of Human-Computer Interaction was interesting but focussing on information technology design seemed, again, to only cover part of the problem. 

Seeking a framework that could help me look at the system as a whole (guidelines, websites, institutions, people, everything), I landed upon behaviour change theory. First I considered the Theoretical Domains Framework (TDF, @caneValidationTheoreticalDomains2012; @michieMakingPsychologicalTheory2005). The TDF was developed to help implementation researchers identify what influences the behaviour of health professionals and patients. It was made by synthesising 33 theories of behaviour and behaviour change into 14 domains that cover the cognitive, affective, social, and environmental influences on behaviour. It was developed to help researchers understand and describe mechanisms of change and why interventions are effective.

<!-- #TODO: sentence about limitations of TDF. Hard to use, not for designing (?), why else did Michie write the BCW? -->

<!-- #TODO: insert BCW description from transfer. -->

# Introduction (Target: 1500)

::: {.SRQR data="Item 3. Problem Formulation: Description and significance of the problem/phenomenon studied; review of relevant theory and empirical work; problem statement."}

My thematic synthesis, survey review, website review, and journal audit generated many hypotheses to explain the limited impact of reporting guidelines. My next question was: what can we, the reporting guideline community, do to address these influences? At this stage in my PhD I wanted to begin including other members of the reporting guideline community. My hopes were two-fold: that capturing perspectives from different stakeholders would generate new ideas, and that by including the community in my work I could somehow bring them along on the journey, cultivate buy-in, and increase the chances that my outputs would lead to change. 

## Working through the Behaviour Change Wheel with the UK EQUATOR Center (Target: 1000)

I expected the Behaviour Change Wheel to be useful in turning a list of barriers into a list of ideas. In their book (@michieBehaviourChangeWheel2014), Michie et al. provide worksheets that guide you through the process of defining the behaviour you are interested, diagnosing barriers in terms of the underlying behavioural drivers, and selecting intervention components. Specifically, these worksheets help you:

1. define the problem in behavioural terms,
2. identify which behaviours could bring about the desired change and selecting one to focus on,
3. specify the chosen target behaviour in terms of who needs to do what, when, where, how often, and with whom,
4. identify what needs to change in order for the target behaviour to occur, and categorize these changes according to their underlying behavioural drivers (from COM-B),
5. identify which intervention functions you could use,
6. identify which policy categories you could use,
7. identify behaviour change techniques (from a taxonomy) based on the intervention functions chosen identified in step 5 and,
8. identify modes of delivery (e.g. face-to-face, internet, mobile app etc.).

I worked through these steps on my own to get a feel for the BCW and whether it could help and to reflect on my own beliefs and ideas. Once familiar, I was able to lead workshops with {{< var counts.EQUATOR_staff >}} members of the UK EQUATOR Centre to go through the process again. 

The EQUATOR team met {{< var counts.EQUATOR_meetings >}} times between December 2021 and May 2022, with each meeting lasting around 2 hours. I would ask everyone to consider the worksheets on their own or in pairs before discussing as a group. Everybody could edit the worksheets, which were shared over Microsoft Teams, but usually only one person acted as a scribe. I withheld my own ideas until the end of a session or task, whereupon others could discuss them and add them to the document if desired. Most of my ideas came from my familiarity with the literature or from my experience as a software developer, and contributing them at such an early stage meant that EQUATOR staff and future focus group members could interrogate, modify and disagree with them. 

My EQUATOR colleagues found the exercise incredibly useful and motivating. For years, the refrain had been that journal enforcement was the only solution. But by the end of the workshops, not only had the team thought of many other strategies, but journal enforcement was now seen as less of a priority and, for some reporting guidelines at least, even undesirable. More fundamentally, the process got everybody thinking about reporting guidelines not just as a set of documents or standards, but as a complex behaviour change intervention. 

The hardest step may have been the third worksheet: selecting our target behaviour. With the behaviour of authors, editors, peer reviewers, and funders so intertwined, and given the variation reporting guideline content and how they are used, specifying a single target behaviour required us to reflect and dissect EQUATOR UK's objectives.

Here is the behavioural specification we ended up with:

<!-- #TODO: insert behavioural specification -->

This was a useful starting point because it made us aware of what we were _not_ focussing on and helped us identify when we were drifting too far from this focus. For example, we purposefully selected _authors_ and although we did still talk about _peer reviewers_ and _editors_ it was only because their behaviour influences the behaviour of authors, and we were aware that their behaviour was "further away" from our true target.

We followed worksheets 1-4 verbatim. Worksheet 4 asks you to identify what needs to change and to categorize these changes into the underlying behavioural driver from the COM-B model. For instance "authors need to know what reporting guidelines are" would be a change under _capability_. "Authors need to be able to access reporting guidelines" would be an _opportunity_ change. My thematic synthesis, survey review, website review and audit provided evidence for many changes, and EQUATOR members contributed their own thoughts based on personal experience.

In the book, worksheet 5 asks you to think about intervention functions at an abstract level and rate them according to the APPEASE criteria, standing for Affordability, Practicability, Effectiveness and cost-effectiveness, Acceptability, Side-effects, and Equity. However, because EQUATOR members weren't familiar with BCW concepts like "environmental restructuring" or "modelling", it felt more productive to take each in turn, talk about the definition, then go through each required change (from worksheet 4) to see how the intervention function could be applied. We used the same technique for worksheets 6 to 8.

The result of our modified worksheet 5 was a list of ideas - things that we, or others, could do. This felt like a good point at which to seek input from other members of the reporting guideline community. 
:::



