#### Deficient component: {{< var intervention-components.design-benefits.title >}}

_Relevant website features: {{< var intervention-components.design-benefits.description >}}_

_Influences addressed: {{< var intervention-components.design-benefits.barriers >}}_

**Participant's described the design as simple, but some parts could be simpler still, and simplicity may come across as basic**

We were aiming to communicate simplicity and that the website was there to help, to make life easier, not more complicated. 

My original design was too simple. Participants described the first version as "clinical" PT-RW, "basic" {{< var pilot.participants.PPT-VS >}}, "just the bones of a website" {{< var pilot.participants.PPT-RW >}}, and although it was "welcoming and straightforward" {{< var pilot.participants.PPT-BH >}}, participants recommended "more vivid colour" {{< var pilot.participants.PPT-MJ >}} or "animations" {{< var pilot.participants.PPT-BH >}}.

The second iteration fared better. The design was still described as "simple", "uncluttered" {{< var pilot.participants.PPT-HA >}}, and as using "white space to emphasise the simplicity of finding what you want to find" {{< var pilot.participants.PPT-HA >}}. Others described the second iteration as "clean" and "uncluttered" {{< var pilot.participants.PPT-HA >}}, "straightforward" and "open" {{< var pilot.participants.PPT-BH >}}, and even as "calming" {{< var pilot.participants.PPT-VS >}}.

The only notable exception was one participant who did not find the top of the SRQR page to look simple: "There's so much going on.
I'm like, where should I read first?" {{< var pilot.participants.PPT-CW >}}

**The tone of voice could be friendlier**

SRQR item 3 asked authors to describe "gaps in current knowledge (the problem statement)". One participant said "I think it it's probably a bit short [...]" and suggested something like  "_'what is currently known about this topic and where do the gaps lie?'_" might be a "friendlier way of writing it" whilst reducing ambiguity {{< var pilot.participants.PPT-VS >}}.

