#### Deficient component: {{< var intervention-components.design-trust.title >}}

_Relevant website features: {{< var intervention-components.design-trust.description >}}_

_Influences addressed: {{< var intervention-components.design-trust.barriers >}}_

When participants talked about trust, they mentioned whether the website came across as professional, credible, and believable. This intervention component is complex because content and design throughout the entire website influenced judgements regarding trust. In particular, participants wanted to know who made the website and why they could be trusted, and identified some design elements that could look more professional. 

**EQUATOR's introduction could be more prominent**

Apart from its logo, EQUATOR was not mentioned at the top of the page. Participants who already knew about EQUATOR said that its brand lent credibility: 

> "and then I picked up the top my top left hand corner with the EQUATOR logo so it seemed from reputable source." {{< var pilot.participants.PPT-VS >}}

> "I already trust the website because I saw that... like this is legit and I see the credentials from EQUATOR network" {{< var pilot.participants.PPT-MJ >}}

Participants unfamiliar with EQUATOR expressed wanting to know who developed the website. Whilst looking at the top of the home page, one participant said:

> "I really don't get an idea of [...] who's responsible for the website [...] would I trust the developers of the website?" {{< var pilot.participants.PPT-OMK >}}

The home page introduced EQUATOR at the very bottom. Participants recommended moving this introduction (or parts of it) up to the top, using an updated photo, and adding EQUATOR's affiliations and awards. 

> "So most places put the _about_ stuff at the bottom and I would have liked to have seen what [EQUATOR stands for] explained right at the top." {{< var pilot.participants.PPT-CW >}}

> "And then this is the thing on the bottom that I want to look at on every website... because I want to see if they have an actual office. So usually I click this "about us" first" {{< var pilot.participants.PPT-RW >}}

<!-- > "Oh, so this is your mission. So here my question is _What is this group? What is EQUATOR?_ So this is my first question because from my background, which is not from medicine, I'm not very familiar with this group. So I want to know what is this and the second feeling I have, I think I might want to see this information at the very first beginning...I want to know who this website is created by. Because I want to use a professional website, so I think the reason I read this paragraph is I want to find some evidence to prove that your group is very professional...Well, maybe you can put [the section about EQUATOR] at the very first beginning and provide a little description about what the group is about, what it is, and what are those people where do they come from something like this." {{< var pilot.participants.PPT-JZ >}}

> "I also did some research with my Chinese colleagues and sometimes some prestigious university's logo will add trust, yeah." {{< var pilot.participants.PPT-YD >}}

> "I think sometimes it is useful [...] to put some awards here. Just to make people think you are trustworthy." {{< var pilot.participants.PPT-JZ >}} -->

**The site's design could be more professional**

I tried to create an aesthetic that would make the website appear simple. The first iteration was apparently _too_ simple and one participant explained how its simplicity made it less trustworthy:

"it looks kind of like a blog [...] it's a basic website" {{< var pilot.participants.PPT-RW >}}

"I wouldn't say [it looks] particularly trustworthy, but not particularly suspicious either. Kind of in the middle [...] something that will be more trustworthy will be something which is more sophisticated because I know, 'OK, this is someone who actually took his time to do a lot of work... put a lot of work in designing it'. Most of the time if it is a fake website, it's usually much more simple." {{< var pilot.participants.PPT-WH >}}

One participant viewed both the first and second iterations of the home page (their second interview session occurred after the iteration), and they described the second iteration as better because "It's like more trustable [...] Scientific. Evidence based. Yeah, of course, legit." {{< var pilot.participants.PPT-MJ >}}

However, one participant still questioned the second iteration's simplicity and trustworthiness, and drew a comparison with another website that she _did_ trust:

> "So I'm saying it's kind of basic, that the format itself is kind of basic [...] [When] I'm looking for information on PUB Med, just the outlet itself gives you the picture that, you know, somehow you can trust it. You know it looks as if there was more work put in it." {{< var pilot.participants.PPT-OMK >}}

**Logos lend credibility and could be more prominent**

Participants noticed that the first iteration had no logos:

> "I don't know if this is just me, but I kinda want some logos. So I know who will
vouch for [the website] right away. Like, usually [...] there's some, like, other medical societies that are, like, "We we are on the EQUATOR network" {{< var pilot.participants.PPT-RW >}}

I added logos to the second iteration's home page to show publishers endorsing reporting guidelines. All participants liked these, but some suggested they could appear at the top of the home page so they are immediately visible.

> "Leading publishers....Wow, this is good...Nature. Really? Elsevier, BMJ. Yes, this is good. And this brings some sense of trust and authenticity in the website." {{< var pilot.participants.PPT-BH >}}

> "[The publishers' logos are] encouraging, because these are all publishing houses with mostly reputable journals, probably all reputable journals. [...] You know, if these were higher up, then [...] that would have made me feel a little bit more like ohh, this is good." {{< var pilot.participants.PPT-CW >}}

**Numbers showing reporting guideline endorsements and citations lend credibility, but may not be intuitive**

The top of the SRQR guideline page included widgets displaying the number of journal endorsements, and the number of times the reporting guideline had been cited. Some people commented that this information lent credibility: 

> "I think it is authentic. It's robust. If it was endorsed by many journals and developed by experienced researchers, if I use it, maybe I'll get a better quality work." {{< var pilot.participants.PPT-BH >}}

> "I think citations here might be some people or some people's work who has cited this page. So this this button [...] might show people how many other words use this page." {{< var pilot.participants.PPT-JZ >}}"

> "...understand [...] that the SRQR guidelines is something that's already widely used."

> "I didn't pay attention before, but I think I like it (the citation information) [...] if it is more cited, I think, like, I will believe it. I will believe it, like, much better, and also like the journal endorsements" {{< var pilot.participants.PPT-YD >}}

However, not everybody understood what these numbers meant.

> "Is this [widget] telling me [something], or is it what I am supposed to click on?" {{< var pilot.participants.PPT-OMK >}}

> "I was a bit confused there, OK" {{< var pilot.participants.PPT-OMK >}}

> "I think the citation tab over here... What is the relevance of it? I mean, why I'm seeing that?" {{< var pilot.participants.PPT-SK >}}

Others were not sure whether the citation information pertained to the website or an underlying article. 

> "I'm not sure if [it is about], you know, the website or connected paper." {{< var pilot.participants.PPT-JZ >}}

> "Has it been cited 4000 times? I don't understand that." {{< var pilot.participants.PPT-CW >}}

**Not everybody considered the image at the top of the home page to be trustworthy**

For the second iteration, I added an image to the top of the home page comprising of three icons to represent the process of writing a manuscript. One participant described this image as a "bit naff [...] I actually think this [image] reduces [the website's] score on the first impressions of trustworthiness kind of thing. Just because [the icons making up the image] are so, umm, ubiquitous, and, uh cheap?" {{< var pilot.participants.PPT-HA >}}