#### Deficient component: {{< var intervention-components.examples.title >}}

**Many participants said they wanted more, varied examples**

Each reporting item in SRQR comes with one or more examples from published literature. All participants stressed the usefulness of these examples. The attention examples received was notable because I did not ask about them; all comments about examples came spontaneously from the participant in the think aloud and plus minus tasks. 

> "Oh, and you have examples that could be really helpful, yeah." {{< var pilot.participants.PPT-MJ >}}

> "the most important thing I would say is the examples" {{< var pilot.participants.PPT-BH >}}

> "I found [this section] very useful as they give more detailed explanations on each specific section, and particularly the examples." {{< var pilot.participants.PPT-WH >}}

However, many participants said they wanted more examples, and greater variation in style, length, and conciseness.

> "need further explanation and examples" {{< var pilot.participants.PPT-BH >}}

> "it would would have been useful or helpful for me to to have more than just one example." {{< var pilot.participants.PPT-OMK >}}

> "illustrations of how to [report] this information in a concise manner, that would be very helpful as well." {{< var pilot.participants.PPT-OMK >}}

> "you may as well put a whole discussion in there, or at least just sort of three or four paragraph discussion" {{< var pilot.participants.PPT-CW >}}

> "And here if there could be more examples, because when I [...] started to read through and understand the the PRISMA guidelines and use the official explanation file to try to understand exactly what I'm required to write about and the examples particularly helped me a lot." {{< var pilot.participants.PPT-WH >}}

Many participants wanted examples from their own field, or even entire publications that have used the guideline:

> "So I want something more relatable, [because] when I was reading these examples they were not relevant to my work." {{< var pilot.participants.PPT-CW >}}

> "...if you can list some [...] papers who use the SRQR, you can put it here." {{< var pilot.participants.PPT-JZ >}}

> "I've searched on pubmed to find an example of a research article that's used these standards so I could copy or check how they've laid it out, which subheadings they've used." {{< var pilot.participants.PPT-CW >}}

**Citations may be less credible if they are old or not referenced**

In the original SRQR publication, all examples are referenced. I had not included references for the examples when putting them onto the website because of time constraints. This bothered one participant.

> "Well, there's no references there, so is that a very good example? No, I don't know the source of these things. [...] You know, I don't know, where did it come from? Where's the reference?" {{< var pilot.participants.PPT-CW >}}

When I asked about hypothetically labelling examples as illustrative if they were made up, the participant said "Yeah, I guess that would be alright". 

The same participant also noted that an example was quite old (10 years). 

**Citations could be more useful if explained or annotated**

Because some reporting items contain multiple sub-items, one participant said annotating examples may be helpful. Taking a discussion item about transferability and integrating findings, they suggested "if you could underline or maybe indicate [in the example] that _this_ [sentence] is now how they are trying to say the result can be transferable, umm, this is another [sentence] trying to say how they're trying to integrate.... something like that." {{< var pilot.participants.PPT-BH >}}

