## Discussion

### Summary of results

My objective was to identify ideas to address factors that may influence adherence to reporting guidelines by running workshops with the EQUATOR Network and focus groups with guideline developers, publishers, and other experts. Stakeholders identified {{< var counts.sub_ideas_pre_jh >}} ideas employing all intervention functions. There were ideas to consider before, during, and after creating reporting guidelines, ideas to consider when creating resources, ideas about tools to assist application, ideas about ongoing activities to support or promote guidance use, and ideas about refining guidance over time in response to feedback. Many of these ideas could be enacted by guideline developers, publishers, and EQUATOR, but participants also saw opportunities for ethics committees, funders, academics, registries, and syllabus writers; stakeholders who are typically less frequently considered.

I believed that including perspectives from a range of stakeholders would lead to more ideas. This seems to be the case: EQUATOR staff thought of {{< var counts.EQUATOR_ideas >}} which was then expanded to {{< var counts.sub_ideas_pre_jh >}} through the focus groups. 

This is the first time that guideline developers from different groups have come together with publishers and academics to consider reporting guideline dissemination as a system. I had a fair response rate from guideline groups and of their responses were generally supportive, even if they were unable to take part. Multiple guideline developers volunteered their guideline to be a "guinneapig" and expressed support for my work. All stakeholders were open minded to the barriers I presented except for one developer who expressed scepticism that reporting guidelines were anything but perfect, and requested additional evidence of authors' negative experiences.

### Implications

These results will be of interest to the reporting guideline community. Guideline developers may find inspiration here when writing or revising guidance. Many of the ideas could be enacted by the EQUATOR Network. At the time of writing, the EQUATOR Network was in the process of updating its advice for guideline developers, which I hope will be informed by these results. The ideas generated may also be of interest to publishers, funders, and Universities.

Although only a few reporting guideline development groups took part in this study, most ideas identified were abstract enough to generalise to most reporting guidance, which tend to be developed and distributed in similar ways; (e.g., all development groups will have to consider what guidance to create, its scope, how to communicate it clearly and how to disseminate it). Some ideas may even generalise to other interventions to encourage good research practices (e.g., to communicate personal benefits, not to patronize researchers). 

### Limitations

The study may have benefited from more diversity in participants' backgrounds and expertise. I could have recruited participants from funders, ethics committees, or registries, behaviour change experts or experts familiar with user experience of websites or written documents. All participants were western and proficient in English. Although this is partly a consequence of who writes reporting guidelines, we could have sought input from publishing houses that cater to non-western authors. Broadening the participant pool in this way would have led to more ideas. 

My focus groups were smaller than I had planned. Some would consider these group sizes too small to be called focus groups, and may instead call them paired interviews, dyads, or triads ([@https://www.skillzone.netDefinitionPairedDepth; @https://www.skillzone.netDefinitionTriad]]). A hallmark of focus groups is that they use "group interaction to produce data" @l.morganFocusGroupsQualitative1997, and these interactions may include sharing experiences and challenging each other. However, I did not feel the small group sizes to be a limitation in this study for two reasons. Firstly, because participants were co-editing a file and building upon the thoughts of previous groups, participants could react and respond to to participants from previous groups.  Secondly, participants had deep understandings of the topic (evidenced by sessions overrunning and participants dwelling on a single topic) which meant that even pairs of participants had plenty to discuss, share, and debate. If I had condensed participants into, say, 3 groups of 5-6 participants, each participants would have had less time to speak and I anticipate that many ideas would have gone un-spoken. 

### Future work

I purposefully did not seek input from authors as this study required input from experts familiar with reporting guideline dissemination. Instead, I describe how I sought input from authors in chapter {{< var chapters.pilot >}}. I also purposefully did not ask stakeholders to prioritize or rank ideas. In chapter {{< var chapters.workshops >}} I explained that prioritization is subjective and, therefore, should be done by stakeholder separately. In the next chapter I describe how I decided which ideas to act on and how I turned them into intervention components.

### Reflections on this chapter

As with chapter {{< var chapters.synthesis >}}, I decided to keep notes on my experience of writing this chapter using the SRQR guideline. I began by writing paragraphs for each guideline item in the order they are presented in the guideline. The resulting text lacked a narrative thread, and I found it difficult to explain how this chapter related to the previous one. As a result, my first draft required a significant re-write. 

I also kept a diary of my experiences running these focus groups. The only time I felt uncomfortable was when talking with senior academics from the reporting guideline community. I did not want to make them feel like I was criticising their work. In my methods section I explained this concern was because I did not want participants to feel defensive or to limit discussion in any way. However, on reflection, I was also aware that these people may one day be my peer reviewers, collaborators, or even employers. So not only did I not want to criticise them, but I wanted to leave a good impression. I navigated these concerns by talking about reporting guidelines in an abstract way (as opposed to focussing on _their_ guideline) and by relying heavily on the behaviour change wheel to structure discussion when necessary. I've already explained how the framework helped participants to brainstorm ideas systematically, but on reflection I also felt it neutralised questions that may otherwise have seemed personal or accusatory.
