
## Introduction

In chapter {{< var chapters.workshops >}} I described how I led reporting guideline experts from the EQUATOR UK Centre through the stages recommended in Michie et al.'s book "The Behaviour Change Wheel - A Guide to Designing Interventions" @michieBehaviourChangeWheel2014. This guide helped us define our target behaviour, identify {{< var counts.barriers >}} factors that may influence this behaviour, and to prioritise lists of intervention functions, policy categories, possible behaviour change techniques, and delivery options. However, these lists were abstract that still had to be _actualised_. For instance, although we had prioritised _Restructuring the physical environment_ as a possible behaviour change technique, _how_ could the environment be restructured? Similarly, we prioritised Enablement, Persuasion, or Education, but _how_ and _where_ could these functions be applied? 

Thus my next objective was to gather concrete ideas on how these abstract concepts could be realised to address reporting guideline limitations. I did this with EQUATOR as part of the workshops described in the previous chapter. However, this was also an opportunity to invite input from broader stakeholders which was important because, although EQUATOR is a key part of the reporting guideline landscape, they are _only_ a part of it. Ultimately, all stakeholders within the academic system influence the impact of reporting guidelines. Guideline developers and publishers arguably do so most directly, and so it was important to draw on their experience and opinions. It hadn't been feasible to include these stakeholders through all stages of the BCW approach as a) the time commitment was too great, b) it would have required stakeholders to become familiar with the framework and its terminologies which was too big an ask. In contrast, brainstorming ideas was a convenient and important stage to include them in. I expected that seeking input from a more diverse group would lead to _more_ ideas and that those ideas would be more likely to gain traction.

In this chapter I explain how I went through this brainstorming process 1) by running workshops with EQUATOR staff members and 2) by running focus groups with other stakeholders before describing the combined results. 

<!-- # ASK Charlotte: is the objective clear, justified, and sign posted? -->
<!-- Although some EQUATOR members have developed reporting guidelines, their experience may not be representative of "external" guideline developers who, despite having a deep understanding of their own guidance, may consider reporting guidelines as a small part of their academic identity and may not "live and breathe" reporting guidelines in the same way EQUATOR does. -->




