# Data saturation

* Often seen as a default marker of quality applied to all qualitative research 
* It gets this badge for two reasons: an indicator of transparency and sample adequacy 
* But not always appropriate, depending on methods and methodology. 
* When researchers talk of saturation they don't always define what they mean. It can refer to theoretical saturation, or data saturation. 
* I did not believe sarturation existed. Although I did think ideas were "out there", I did not believe they were finite. If I 
* I did count and report new codes. I did this to be transparent, but not because I believed it proved my sample was adequate. My sample was adequate because it generated lots of answers to my research question. However, I did not believe 


* Comes from Glaser and Strauss' grounded theory
* "Glaser and Strauss’ grounded theory describes the way in which social research reveals patterns in data that can then be used to generate theories and hypotheses on which further research can be done (this is in contrast to quantitative research, where pre-existing hypotheses form a framework for research)."
* 'The criterion for judging when to stop sampling the different groups pertinent to a category is the category’s theoretical saturation. Saturation means that no additional data are being found whereby the sociologist can develop properties of the [theoretical] category. As he sees similar instances over and over again, the researcher becomes empirically confident that a category is saturated.'

## O'Reilly and Parker

### ‘Unsatisfactory Saturation’:a critical exploration of the notion of saturated sample sizes in qualitative research

https://journals.sagepub.com/doi/epdf/10.1177/1468794112446106?src=getftr

* They note Data saturation comes from grounded theory and has been translated to other qualitative approaches but that it is not always appropriate. However, many journals and reviewers expect it by default as a marker of quality and transparency 
* "Thus, sampling in qualitative research is concerned with the richness of information (Kuzel, 1992) and the number of participants required, therefore, depends on the nature of the topic and the resources available(Gaskell, 2000). There are two key considerations that guide the sampling methods in qualitative research, appropriateness and adequacy (Morse and Field, 1995). It is argued,therefore, that the researcher should be pragmatic and flexible in their approach to sampling and that an **adequate sample size is one that sufficiently answers the research question** (Marshall, 1996).In this sense then generalizability is not sought by the researcher and the focus is lesson sample size and more on sample adequacy (Bowen, 2008). Bowen argues that adequacy of sampling relates to the demonstration that saturation has been reached, which means that depth as well as breadth of information is achieved. Qualitative researchers often make decisions related to the adequacy of their sample based on the notion of saturation."
* Transparency is an important marker of quality in qualitative research, and being transparent about whether, how, and why saturation was reached is important. 
* thematic/data saturation are normatively taken to mean that data should continue to be collected until nothing new is generated (Green and Thorogood, 2004); the point at which there are fewer surprises and there are no more emergent patterns in the data (Gaskell, 2000). This is quite different to theoretical saturation, the form of saturation used by grounded theorists.The original meaning of saturation pioneered within grounded theory, of theoretical saturation, is still used within this approach in current work and has retained its central importance. In grounded theory the notion of saturation does not refer to the point at which no new ideas emerge, but rather means that categories are fully accounted for, the variability between them are explained and the relationships between them are tested and validated and thus a theory can emerge (Green and Thorogood, 2004). This is congruent with the underpinning epistemological position and the goals of grounded theory, which are to develop an explanatory theory of the social processes that are studied in the environments in which they have taken place (Glaser and Strauss, 1967; Starks and Trinidad,2007)
* In reality there are practical constraints on the researcher in terms of unforeseen participant194 Qualitative Research 13(2)attrition (Tuckett, 2004) and in terms of time and resources (Green and Thorogood,2004). This is particularly important as there are arguments relating to saturation and quality within each interview and, therefore, researchers need to pay attention to both the length of interviews as well as the number of interviews (Onwuegbuzie and Leech,2005). Transparency about these limitations on reaching saturation does not necessarily invalidate the findings. If saturation is not reached this simply means that the phenomenon has not yet been fully explored rather than that the findings are invalid (Morse,1995)
* Saturation is a convincing concept but has a number of practical weaknesses, especially as in some cases the number of emergent themes are potentially limitless (Greenand Thorogood, 2004). This is because each life is unique and in this sense data are never truly saturated as there will always be new things to discover (Wray et al., 2007)
* Caelli et al. further argue that research-ers must address their theoretical position, evidence the congruence between methodol-ogy and methods, and highlight the strategies they used to establish rigour. What thismeans is that the concept of saturation is not always an appropriate criterion for estab-lishing quality across all qualitative approaches. (Although the passage goes on to say that saturation is commonly used in interviews and focus groups)

