---
title: "What facilitators and barriers might researchers encounter when using reporting guidelines? Part 2: Describing the questions asked in quantitative surveys."
format: 
    html:
        output-file: index.html
    docx:
        output-file: JH-chapter-survey-content.docx
---

::: {.callout}
I am reworking the survey review article into a chapter.   

Known todos:

* Fix table 4 formatting
* Move definitions and appendicies to thesis appendix

:::

## Background 

In the previous chapter I describe my systematic search and thematic synthesis of qualitative research exploring authors' experiences of using reporting guidelines. I identified potential influences that may affect whether an author adheres to reporting guidelines. During my search, I observed that many studies also included quantitative survey questions, and despite not considering them in my qualitative synthesis, I felt that these questions were important to investigate for two reasons. Firstly, as many of the researchers designing these surveys were themselves users or developers of reporting guidelines the questions may reflect real barriers or facilitators that they have experienced, witnessed, or are trying to avoid or achieve. Secondly, in mixed-method surveys, quantitative questions may bias responses to subsequent qualitative questions and, therefore, the findings of my thematic synthesis. For instance, qualitative questions like "Anything else?" or "Please elaborate" may lead respondents to neglect or repeat topics covered by the previous quantitative questions.

In this study, I describe the landscape and content of quantitative surveys that solicit information on author experience of using reporting guidelines. My aim was to identify additional possible influences that were absent from the qualitative evidence synthesis.

## Methods

My qualitative synthesis included a systematic search that sought to capture all survey studies investigating reporting guidelines (see (in press) for full search details). I found 22 studies that included quantitative survey questions, 14 of which also included one or more qualitative questions (see @tbl-study-list). YD translated two studies from Chinese into English[@fangSurveyAwarenessARRIVE2015; @maSurveyBasicMedical2017]. I imported files into NVivo, including the full surveys where available, labelled all questions with descriptive codes, creating new codes when necessary, and then inductively grouped related codes into broad categories (see @tbl-codes-from-quant).

## Results

### What reporting guidelines were studied?

Between the 22 studies 25 reporting guidelines were mentioned, most frequently PRISMA (n=6), STARD (n=6), CONSORT (n=6) and ARRIVE (n=5) (see my [List of Abbreviations](/chapters/abbreviations.qmd) for the full titles of each reporting guideline). Thus, only a small proportion of the reporting guidelines indexed in EQUATOR's database [@EQUATORNetworkEnhancing] have been evaluated with quantitative questions. Fourteen studies focussed on a single guideline (n=14), with others asking questions about multiple guidelines (e.g. "which reporting guidelines [participants] had known"[@girayAssessmentKnowledgeAwareness2020a]) or guidelines in general (e.g., "whether they had used reporting guidelines in their publications"[@karadagoncelKnowledgeAwarenessOptimal2018a]). Most studies included participants from the USA, Europe, and Canada and only a few studies conducted elsewhere (e.g., China and Turkey) (see @tbl-study-list).

In comparison, my thematic synthesis (chapter {{< var chapters.synthesis >}}) identified 18 studies that collected qualitative data. These studies covered only 12 reporting guidelines and were all conducted in western countries, hence were slightly less diverse than the quantitative survey studies.

### The focus of quantitative questions

Survey studies asked participants:

-   whether they were aware or familiar with certain reporting guidelines,
-   how often they used them and what for,
-   whether reporting guidelines had influenced their behaviour,
-   whether guidance was usable and useful,
-   their opinions on guidance content,
-   their reasons for using a reporting guideline,
-   their opinions on reporting quality in the literature,
-   whether reporting guidelines were easy to find and access,
-   whose role it was to check for compliance,
-   whether the aim of the guidance was clear, and
-   opinions on things explicitly named as a barrier including the length of the guidance, the language it is written in, and the time needed to use it.
-   opinions on things explicitly named as a facilitator or motivator including endorsements, evidence, explanatory information, training, the behaviour of peers, and the development process of the guidance.

### Comparing the focus of quantitative questions with themes derived from qualitative data

The quantitative questions included some novel influences not contained in the qualitative data (shown in bold in @tbl-codes-from-quant), such as training as a possible facilitator [@fullerWhatAffectsAuthors2015], whether authors had heard of the EQUATOR Network [@fullerWhatAffectsAuthors2015; @girayAssessmentKnowledgeAwareness2020a], and whether transparency in guideline development is important [@fullerWhatAffectsAuthors2015]. One study asked whether language may be a barrier to using reporting guidelines for some[@pragerBarriersReportingGuideline2021]. This concern may have been missing from the qualitative studies because they were conducted in English. Both quantitative questions and the qualitative data mentioned journals enforcing reporting guidelines, but only quantitative questions asked whether funders and employers should also enforce them.

Most ideas captured in the quantitative questions also appeared in the qualitative data. This may indicate that the quantitative questions asked were pertinent, or perhaps that they influenced participants' responses to subsequent, qualitative questions, as mixed method surveys were included in this commentary and the qualitative synthesis.

Overall, although the qualitative questions contained some novel themes, I found that the qualitative data contained many more ideas that were not addressed by the quantitative questions (see bold items in @tbl-codes-from-qual). These included what authors understand reporting guidelines to be, the pros and cons of itemization, ideas of how guidance could be improved, negative feelings when an item cannot be reported as desired, the pros and cons of including design advice in reporting guidance, whether optional items were understood as being optional, and frustration when the scope of a reporting guideline is too broad, narrow, or unclear.

The qualitative data sometimes provided context to or explanation for quantitative answers (see italicised items in @tbl-codes-from-qual). For example, many of the quantitative surveys asked participants whether they could understand the guidance. However, a quantitative answer to this question does not reveal *what* the participant understands, *how* they understand it, or whether they understand it *as intended*. The qualitative data contained reports of people failing to understand the wording of an item, how to report that item in practice, whether an item applies to them, whether a reporting guideline applies to them, what the intended scope of a reporting guideline is, or even what a reporting guideline is at all. One study found that although authors reported understanding an item, their writing showed that they had interpreted it differently to how the reporting guideline developers had intended[@daviesFindingsNovelApproach2016].

## Advice for future studies

As very few reporting guidelines have undergone any kind of user testing, I urge guideline developers to evaluate their resources to ensure researchers understand their content, aim, and applicability criteria. Advice on how to go about this could be included in an update of guidance for guideline developers, the current version of which contains little advice on how to evaluate reporting guidelines[@moherGuidanceDevelopersHealth2010].

Because quantitative surveys can miss or mask important findings, developers seeking actionable feedback should collect qualitative data when assessing how researchers understand or feel about reporting guidelines, or what could be done to improve the guidance. As survey studies are subject to recall bias when participants are describing past behaviour or opinions, future studies could consider methods that allow researchers to document experiences in real time, like observation or think aloud tasks.

Studies should ensure participants represent expected users in terms of academic writing experience, discipline, profession, experience (or naivety) with reporting guidelines, and language, or even focus on differential experiences of specific target groups. For example, the EQUATOR Network website gets similar levels of traffic from Asia and Europe, yet very little research into usability or barriers of reporting guidelines has included authors from Asian countries (see chapter {{< var chapters.web-audit >}}). The website also sees many new visitors who abandon the site quickly, without accessing any reporting guidance. These visitors may be authors who are naïve to reporting guidelines and decide not to use one. Most of the included studies used snowball sampling or required authors to read the guidance as part of the study itself, and so don't capture perspectives of these less-engaged authors.

Surveys should avoid leading questions. For example, the Likert rated statements "The STARD 2015 guidelines are easy to follow" [@pragerBarriersReportingGuideline2021] and "The time required to adhere to the STARD 2015 guidelines is a barrier to using the guidelines" [@pragerBarriersReportingGuideline2021] are both subject to acquiescence bias; the tendency for participants to agree with research statements [@lavrakasAcquiescenceResponseBias2008]. Future studies should consider using neutral questions, such as "Do you think the STARD 2015 guidelines are easy to follow?".

Studies used lots of different words to describe reporting guidelines, including *guidelines, standards, requirements, checklist, example and elaboration,* or just an acronym, e.g., CONSORT. This became a problem in studies where participants were not supplied with guidance documents as part of the study, as it was not always clear which document a participant was considering. For instance, asking participants whether PRISMA is easy to understand will not tell you whether they are talking about the PRISMA checklist, statement, or explanation and elaboration document. Future studies should be specific when asking questions and reporting results.

## Discussion

Very few reporting guidelines have been evaluated using either quantitative or qualitative methods. Reviewing the content of quantitative surveys revealed some novel influences which were absent from the qualitative data synthesised in chapter {{< var chapters.synthesis >}}. Quantitative surveys often asked about awareness, usage, usability, usefulness, importance, barriers, facilitators, content, and whether reporting guidelines had led to a change in behaviour but did not address many other themes identified in my qualitative synthesis. Reporting guideline developers who want to make sure their resources are easy to use should consider using qualitative methods, which may produce richer, actionable insights.

Two studies asked participants whether they had heard of the EQUATOR Network, noting that it is a "a valuable resource for users and potential users of reporting guidelines" that 44% (19/43) of editors[@fullerWhatAffectsAuthors2015] and 38% of authors (38/100) [@girayAssessmentKnowledgeAwareness2020a] are aware of. Although these studies asked participants whether they were familiar with EQUATOR, authors' experiences of using EQUATOR's website has never been explored.

In the next chapter I describe EQUATOR's website and key characteristics of its web traffic, before discussing how well it is helping authors find reporting guidance and what may be limiting its success.

# Tables

  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  **Citation**                                                                               **Title**                                                                                                                                                                                    **Guidelines studied**                                                                                                                                                                                                                **Sample geographics**                                                                                                                                                               **Sample size**   **Quantitative or mixed methods**
  --------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ----------------- -----------------------------------
  Brouwers et al. 2016 [@brouwersAGREEReportingChecklist2016]                             The AGREE Reporting Checklist: a tool to improve reporting of clinical practice guidelines                                                                                                   AGREE Reporting Checklist                                                                                                                                                                                                             Not reported                                                                                                                                                                         15                Quantitative

  Burford, Welch, Waters et al., 2013 [@burfordTestingPRISMAEquity20122013]                Testing the PRISMA-Equity 2012 reporting guideline: the perspectives of systematic review authors                                                                                            PRISMA-Equity Checklist items embedded into survey                                                                                                                                                                                    Not reported                                                                                                                                                                         151               Mixed methods

  Davies, Donnelly, Goodman, Ogrinc 2016 [@daviesFindingsNovelApproach2016]                Findings from a novel approach to publication guideline revision: user road testing of a draft version of SQUIRE 2.0                                                                         SQUIRE Guidelines, which are presented as a checklist                                                                                                                                                                                 Not reported but invited participants were from USA, UK Lebanon, Sweden.                                                                                                             44                Mixed methods

  Dewey, Levine, Bossuyt et al., 2019 [@deweyImpactPerceivedValue2019]                     Impact and perceived value of journal reporting guidelines among Radiology authors and reviewers                                                                                             CONSORT, STROBE, PRISMA, STARD checklists                                                                                                                                                                                             USA, Canada, China, South Korea, Japan, Germany, France , Italy, UK, Other European countries, Middle East, Latin America and 'Other'.                                               831               Mixed methods

  Eysenbach, 2013 [@eysenbachg.CONSORTEHEALTHImplementationChecklist2013]                  CONSORT-EHEALTH: Implementation of a Checklist for Authors and editors to improve reporting of web-based and mobile randomized controlled trials                                             CONSORT-Ehealth checklist                                                                                                                                                                                                             Not reported                                                                                                                                                                         61                Mixed methods

  Fang, Xi, Liu et al. 2016 [@fangSurveyAwarenessARRIVE2015]                              A survey on awareness of the ARRIVE Guideline and GSPC in researchers field in animal experiments field in Lanzhou City                                                                      ARRIVE Guidelines and Gold Standard Publication Checklist                                                                                                                                                                             China                                                                                                                                                                                287               Quantitative

  Fuller, Pearson, Peters, Anderson, 2015 [@fullerWhatAffectsAuthors2015]                  What affects authors' and editors' use of reporting guidelines? Findings from an online survey and qualitative interviews                                                                    TREND and reporting guidelines in general                                                                                                                                                                                             Predominantly North America                                                                                                                                                          56                Mixed methods

  Giray et al. 2020 [@girayAssessmentKnowledgeAwareness2020a]                              Assessment of the knowledge and awareness of a sample of young researcher physicians on reporting guidelines and the EQUATOR network: A single center cross-sectional study                  CONSORT, PRISMA, CARE, GRASS, STARD, STROBE, ARRIVE, SAMPL guidelines                                                                                                                                                                 Turkey                                                                                                                                                                               100               Quantitative

  Guo, Qi, Yang et al., 2018 [@guoRecognitionStatusQuality2018]                            Recognition status of quality assessment and standards for reporting randomized controlled trials of traditional Chinese medicine researchers                                                CONSORT Statement, STRICTA guidelines and CONSORT extension for Traditional Chinese Medicine                                                                                                                                          China                                                                                                                                                                                180               Quantitative

  Korevaar, Cohen, Reitsma, et al, 2016 [@korevaarUpdatingStandardsReporting2016]          Updating standards for reporting diagnostic accuracy: the development of STARD 2015                                                                                                          STARD checklist                                                                                                                                                                                                                       Not reported for quantitative survey                                                                                                                                                 12                Mixed methods

  Ma et al. 2017 [@maSurveyBasicMedical2017]                                               Survey of basic medical researchers on the awareness of animal experimental designs and reporting standards in China                                                                         ARRIVE guidelines and Gold Standard Publication Checklist                                                                                                                                                                             China                                                                                                                                                                                266               Quantitative

  Macleod, Collings, Graf et al. 2021 [@macleodMDARMaterialsDesign2021]                    The MDAR (Materials Design Analysis Reporting) Framework for transparent reporting in the life sciences                                                                                      MDAR checklist                                                                                                                                                                                                                        USA, China, Japan, Germany, Other EU, 'Other'                                                                                                                                        211               Mixed methods

  McDonough et al. 2011 [@mcdonoughj.FamiliarityNonindustryAuthors2011]                    Familiarity of non-industry authors with good publication practice and clinical data reporting guidelines                                                                                    CONSORT guidelines                                                                                                                                                                                                                    USA, UK, Canada\                                                                                                                                                                     23                Quantitative
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                South Africa, Israel,\                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                China                                                                                                                                                                                                  

  Öncel et al. 2018 [@karadagoncelKnowledgeAwarenessOptimal2018a]                          Knowledge and awareness of optimal use of reporting guidelines in paediatricians: A cross-sectional study                                                                                    CONSORT guidelines, STROBE, PRISMA, CARE, SRQR, STARD, SQUIRE, CHEERS, SPIRIT, ARRIVE, TREND, STREGA, the Conference on Guideline Standardization (COGS), Outbreak Reports and Intervention Studies Of Nosocomial infection (ORION)   Turkey                                                                                                                                                                               244               Quantitative

  Page, McKenzie, Bossuyt et al. 2021 [@pageUpdatingGuidanceReporting2021]                Updating guidance for reporting systematic reviews: development of the PRISMA 2020 statement                                                                                                 PRISMA statement                                                                                                                                                                                                                      Not reported                                                                                                                                                                         110               Mixed methods

  Prady & MacPherson 2007 [@pradyAssessingUtilityStandards2007]                            Assessing the Utility of the Standards for Reporting Trials of Acupuncture (STRICTA): A survey of authors                                                                                    STRICTA                                                                                                                                                                                                                               Not reported                                                                                                                                                                         28                Mixed methods

  Prager, Gannon, Bowdridge et al. 2021 [@pragerBarriersReportingGuideline2021]            Barriers to reporting guideline adherence in point-of care ultrasound research: a cross- sectional survey of authors and journal editors                                                     STARD                                                                                                                                                                                                                                 Not reported                                                                                                                                                                         18                Mixed methods

  Phillips et al 2015 [@phillipsa.PilotTestingGuideline2015]                               Pilot testing of the Guideline for Reporting of Evidence-Based Practice Educational Interventions and Teaching (GREET)                                                                       GREET checklist and E&E                                                                                                                                                                                                               Not reported                                                                                                                                                                         31                Quantitative

  Rader, Mann, Stransfield et al., 2014 [@radert.MethodsDocumentingSystematic2014]         Methods for documenting systematic review searches: a discussion of common issues                                                                                                            PRISMA statement                                                                                                                                                                                                                      Not reported                                                                                                                                                                         263               Mixed methods

  Sharp, Glonti, Hren, 2020 [@sharpUsingSTROBEStatement2019]                              Using the STROBE statement: survey ﬁndings emphasized the role of journals in enforcing reporting guidelines                                                                                 STROBE statement                                                                                                                                                                                                                      The full survey was answered by participants in Africa, Asia, Europe, North and South America, Middle East, and Pacific Region. It is unclear who answered the free text question.   1015              Mixed methods

  Struthers, Harwood, de Beyer et al., 2021 [@struthersGoodReportsDevelopingWebsite2021]   GoodReports: developing a website to help health researchers find and use reporting guidelines                                                                                               Reporting guidelines in general                                                                                                                                                                                                       Not reported                                                                                                                                                                         274               Mixed methods

  Tam, Tang, Woo, Goh 2019 [@tamPerceptionPreferredReporting2019]                          Perception of the Preferred Reporting Items for Systematic Reviews and Meta Analyses (PRISMA) statement of authors publishing reviews in nursing journals: a cross-sectional online survey   PRISMA statement                                                                                                                                                                                                                      Not reported                                                                                                                                                                         230               Mixed methods
  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

: Studies that collected quantitative data to explore researcher's experiences of reporting guidelines {#tbl-study-list}

  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  **Code**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                **Category**
  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -------------------------------
  Participant's experience [@burfordTestingPRISMAEquity20122013; @daviesFindingsNovelApproach2016; @deweyImpactPerceivedValue2019; @fangSurveyAwarenessARRIVE2015; @fullerWhatAffectsAuthors2015; @girayAssessmentKnowledgeAwareness2020a; @guoRecognitionStatusQuality2018; @karadagoncelKnowledgeAwarenessOptimal2018a; @korevaarUpdatingStandardsReporting2016; @maSurveyBasicMedical2017; @mcdonoughj.FamiliarityNonindustryAuthors2011; @pragerBarriersReportingGuideline2021; @sharpUsingSTROBEStatement2019]   Demographics

  Participant's speciality [@burfordTestingPRISMAEquity20122013; @daviesFindingsNovelApproach2016; @fangSurveyAwarenessARRIVE2015; @fullerWhatAffectsAuthors2015; @girayAssessmentKnowledgeAwareness2020a; @korevaarUpdatingStandardsReporting2016; @maSurveyBasicMedical2017; @pragerBarriersReportingGuideline2021; @radert.MethodsDocumentingSystematic2014; @sharpUsingSTROBEStatement2019; @tamPerceptionPreferredReporting2019]                                                                                   

  Participant's age [@fangSurveyAwarenessARRIVE2015; @girayAssessmentKnowledgeAwareness2020a; @guoRecognitionStatusQuality2018; @karadagoncelKnowledgeAwarenessOptimal2018a; @maSurveyBasicMedical2017; @pragerBarriersReportingGuideline2021; @sharpUsingSTROBEStatement2019; @tamPerceptionPreferredReporting2019]                                                                                                                                                                                                       

  Participant's gender [@fangSurveyAwarenessARRIVE2015; @girayAssessmentKnowledgeAwareness2020a; @guoRecognitionStatusQuality2018; @karadagoncelKnowledgeAwarenessOptimal2018a; @pragerBarriersReportingGuideline2021; @sharpUsingSTROBEStatement2019; @tamPerceptionPreferredReporting2019]                                                                                                                                                                                                                                

  Participant's geography [@deweyImpactPerceivedValue2019; @fullerWhatAffectsAuthors2015; @mcdonoughj.FamiliarityNonindustryAuthors2011; @sharpUsingSTROBEStatement2019]                                                                                                                                                                                                                                                                                                                                                            

  Participant's stage of current research project [@burfordTestingPRISMAEquity20122013]                                                                                                                                                                                                                                                                                                                                                                                                                                                 

  Awareness of a particular guideline [@burfordTestingPRISMAEquity20122013; @fangSurveyAwarenessARRIVE2015; @fullerWhatAffectsAuthors2015; @girayAssessmentKnowledgeAwareness2020a; @karadagoncelKnowledgeAwarenessOptimal2018a; @maSurveyBasicMedical2017; @mcdonoughj.FamiliarityNonindustryAuthors2011; @pradyAssessingUtilityStandards2007; @pragerBarriersReportingGuideline2021; @sharpUsingSTROBEStatement2019; @tamPerceptionPreferredReporting2019]                                                            Awareness

  **Awareness of EQUATOR [@fullerWhatAffectsAuthors2015; @girayAssessmentKnowledgeAwareness2020a]**                                                                                                                                                                                                                                                                                                                                                                                                                                    

  How did they first hear about guidelines or EQUATOR? [@fullerWhatAffectsAuthors2015; @karadagoncelKnowledgeAwarenessOptimal2018a; @sharpUsingSTROBEStatement2019]                                                                                                                                                                                                                                                                                                                                                                  

  When did they first learn about a guideline? [@fullerWhatAffectsAuthors2015]                                                                                                                                                                                                                                                                                                                                                                                                                                                          

  How frequently do they use guidelines? [@burfordTestingPRISMAEquity20122013; @daviesFindingsNovelApproach2016; @deweyImpactPerceivedValue2019; @fullerWhatAffectsAuthors2015; @girayAssessmentKnowledgeAwareness2020a; @karadagoncelKnowledgeAwarenessOptimal2018a; @pragerBarriersReportingGuideline2021; @sharpUsingSTROBEStatement2019; @tamPerceptionPreferredReporting2019]                                                                                                                                             Usage

  When should guidelines be used? [@deweyImpactPerceivedValue2019; @fullerWhatAffectsAuthors2015; @girayAssessmentKnowledgeAwareness2020a; @karadagoncelKnowledgeAwarenessOptimal2018a; @pragerBarriersReportingGuideline2021; @sharpUsingSTROBEStatement2019]                                                                                                                                                                                                                                                                    

  Would they use a guideline, hypothetically [@brouwersAGREEReportingChecklist2016; @burfordTestingPRISMAEquity20122013; @sharpUsingSTROBEStatement2019]                                                                                                                                                                                                                                                                                                                                                                            

  Did the guidance impact subsequent behaviour? [@brouwersAGREEReportingChecklist2016; @burfordTestingPRISMAEquity20122013; @daviesFindingsNovelApproach2016; @deweyImpactPerceivedValue2019; @eysenbachg.CONSORTEHEALTHImplementationChecklist2013; @pradyAssessingUtilityStandards2007; @struthersGoodReportsDevelopingWebsite2021]                                                                                                                                                                                            Impact on behaviour

  Is the guidance usable? [@phillipsa.PilotTestingGuideline2015; @pragerBarriersReportingGuideline2021; @sharpUsingSTROBEStatement2019]                                                                                                                                                                                                                                                                                                                                                                                              Usability

  Is the guidance easy to understand? [@daviesFindingsNovelApproach2016; @guoRecognitionStatusQuality2018; @korevaarUpdatingStandardsReporting2016; @pragerBarriersReportingGuideline2021; @sharpUsingSTROBEStatement2019; @struthersGoodReportsDevelopingWebsite2021]                                                                                                                                                                                                                                                            

  Is the guidance useful? [@brouwersAGREEReportingChecklist2016; @deweyImpactPerceivedValue2019; @fullerWhatAffectsAuthors2015; @maSurveyBasicMedical2017; @macleodMDARMaterialsDesign2021; @sharpUsingSTROBEStatement2019; @struthersGoodReportsDevelopingWebsite2021]                                                                                                                                                                                                                                                         Usefulness

  Is the guidance important? [@daviesFindingsNovelApproach2016; @eysenbachg.CONSORTEHEALTHImplementationChecklist2013; @fullerWhatAffectsAuthors2015; @guoRecognitionStatusQuality2018; @maSurveyBasicMedical2017; @tamPerceptionPreferredReporting2019]                                                                                                                                                                                                                                                                           Importance

  Are time and length barriers? [@eysenbachg.CONSORTEHEALTHImplementationChecklist2013; @fullerWhatAffectsAuthors2015; @pragerBarriersReportingGuideline2021; @sharpUsingSTROBEStatement2019; @struthersGoodReportsDevelopingWebsite2021]                                                                                                                                                                                                                                                                                          Barriers

  **Is language of guidance a barrier? [@pragerBarriersReportingGuideline2021]**                                                                                                                                                                                                                                                                                                                                                                                                                                                        

  Are guidelines lacking for study type? [@fullerWhatAffectsAuthors2015]                                                                                                                                                                                                                                                                                                                                                                                                                                                                

  Is the layout OK? [@brouwersAGREEReportingChecklist2016; @korevaarUpdatingStandardsReporting2016; @sharpUsingSTROBEStatement2019]                                                                                                                                                                                                                                                                                                                                                                                                 Opinions on content

  Should the content be modified? [@brouwersAGREEReportingChecklist2016; @korevaarUpdatingStandardsReporting2016; @pageUpdatingGuidanceReporting2021]                                                                                                                                                                                                                                                                                                                                                                               

  Is the guidance relevant? [@struthersGoodReportsDevelopingWebsite2021]                                                                                                                                                                                                                                                                                                                                                                                                                                                                

  Are guidelines prescriptive? [@fullerWhatAffectsAuthors2015]                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

  Will using a guideline benefit the manuscript? [@brouwersAGREEReportingChecklist2016; @burfordTestingPRISMAEquity20122013; @pragerBarriersReportingGuideline2021; @sharpUsingSTROBEStatement2019]                                                                                                                                                                                                                                                                                                                                Reasons for using a guideline

  Productivity benefits of using guidelines [@sharpUsingSTROBEStatement2019]                                                                                                                                                                                                                                                                                                                                                                                                                                                           

  Using guidelines because of journal requirements [@fullerWhatAffectsAuthors2015; @sharpUsingSTROBEStatement2019]                                                                                                                                                                                                                                                                                                                                                                                                                    

  **Using guidelines because of funder requirements** [@fullerWhatAffectsAuthors2015]                                                                                                                                                                                                                                                                                                                                                                                                                                                   

  **Using guidelines because of employment requirements** [@fullerWhatAffectsAuthors2015]                                                                                                                                                                                                                                                                                                                                                                                                                                               

  Using guidelines because of other researchers expecting it [@sharpUsingSTROBEStatement2019]                                                                                                                                                                                                                                                                                                                                                                                                                                          

  Opinions on reporting quality of the literature [@fangSurveyAwarenessARRIVE2015; @fullerWhatAffectsAuthors2015; @maSurveyBasicMedical2017; @pragerBarriersReportingGuideline2021]                                                                                                                                                                                                                                                                                                                                             Opinions on reporting quality

  Are guidelines easy to find and access [@fullerWhatAffectsAuthors2015; @maSurveyBasicMedical2017; @pragerBarriersReportingGuideline2021]                                                                                                                                                                                                                                                                                                                                                                                            Accessibility

  Who should complete the checklist? [@fullerWhatAffectsAuthors2015; @pragerBarriersReportingGuideline2021]                                                                                                                                                                                                                                                                                                                                                                                                                            Roles

  Are endorsements a facilitator? [@fullerWhatAffectsAuthors2015]                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Facilitators and motivators

  Is evidence of increased chance of publication a facilitator? [@fullerWhatAffectsAuthors2015]                                                                                                                                                                                                                                                                                                                                                                                                                                         

  Is evidence of improved reporting quality a facilitator? [@fullerWhatAffectsAuthors2015]                                                                                                                                                                                                                                                                                                                                                                                                                                              

  Is explanatory information a facilitator? [@fullerWhatAffectsAuthors2015]                                                                                                                                                                                                                                                                                                                                                                                                                                                             

  **Is training a facilitator? [@fullerWhatAffectsAuthors2015]**                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

  Is the behaviour of peers a facilitator or motivator? [@fullerWhatAffectsAuthors2015]                                                                                                                                                                                                                                                                                                                                                                                                                                                 

  Is the evidence base underlying a reporting guideline a motivator? [@fullerWhatAffectsAuthors2015]                                                                                                                                                                                                                                                                                                                                                                                                                                    

  **Is transparency in guideline development a motivator? [@fullerWhatAffectsAuthors2015]**                                                                                                                                                                                                                                                                                                                                                                                                                                             

  Is the aim of the guidance clear? [@korevaarUpdatingStandardsReporting2016]                                                                                                                                                                                                                                                                                                                                                                                                                                                           Aim of guidance
  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

: Codes describing the focus of questions asked and their code categories. Items in bold did not appear in the qualitative data. {#tbl-codes-from-quant}

+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| Codes                                                                                                                                                                                                                                                                                     | Descriptive Themes                                                                     |
+===========================================================================================================================================================================================================================================================================================+========================================================================================+
| *What does this term mean? [@daviesFindingsNovelApproach2016; @daviesSQUIREGuidelinesEvaluation2015; @korevaarUpdatingStandardsReporting2016; @pageUpdatingGuidanceReporting2021; @struthersGoodReportsDevelopingWebsite2021]*                                                      | What does this mean?                                                                   |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| *What does this item mean?* [@daviesFindingsNovelApproach2016; @daviesSQUIREGuidelinesEvaluation2015; @korevaarUpdatingStandardsReporting2016; @pageUpdatingGuidanceReporting2021; @pradyAssessingUtilityStandards2007; @struthersGoodReportsDevelopingWebsite2021]                | Why is this item important?                                                            |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| *How are these items different?* [@daviesSQUIREGuidelinesEvaluation2015; @eysenbachg.CONSORTEHEALTHImplementationChecklist2013; @pageUpdatingGuidanceReporting2021; @pradyAssessingUtilityStandards2007]                                                                             | **Does this apply to me?**                                                             |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| *Have I understood this as intended? [@daviesFindingsNovelApproach2016; @daviesSQUIREGuidelinesEvaluation2015]*                                                                                                                                                                        | **I don't understand what reporting guidelines are**                                   |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| *Examples help me understand items* [[CSL STYLE ERROR: reference with no printed form.]; @pageUpdatingGuidanceReporting2021; @devriesProtocolFormatPreparation2015]                                                                                                                 |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| *Why is this item important?* [@daviesSQUIREGuidelinesEvaluation2015; @korevaarUpdatingStandardsReporting2016; @pageUpdatingGuidanceReporting2021; @tamPerceptionPreferredReporting2019]                                                                                             |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| *Who is this item important to? [@daviesSQUIREGuidelinesEvaluation2015; @pageUpdatingGuidanceReporting2021; @sharpOnlineSurveySTROBE2020]*                                                                                                                                            |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| ***Have I understood the guideline's scope as intended? [@pageUpdatingGuidanceReporting2021; @struthersGoodReportsDevelopingWebsite2021]***                                                                                                                                            |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| ***Does this item apply to me?*** [@daviesSQUIREGuidelinesEvaluation2015; @eysenbachg.CONSORTEHEALTHImplementationChecklist2013; @pageUpdatingGuidanceReporting2021; @pradyAssessingUtilityStandards2007; @struthersGoodReportsDevelopingWebsite2021]                               |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| ***Is this item optional? [@daviesSQUIREGuidelinesEvaluation2015; @pradyAssessingUtilityStandards2007]***                                                                                                                                                                              |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **What are reporting guidelines? [@pragerBarriersReportingGuideline2021; @sharpOnlineSurveySTROBE2020]**                                                                                                                                                                               |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **How should I use a reporting guideline? [@fullerWhatAffectsAuthors2015]**                                                                                                                                                                                                             |                                                                                        |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| I find guidelines useful in general [@deweyImpactPerceivedValue2019; @struthersGoodReportsDevelopingWebsite2021]                                                                                                                                                                       | Guidelines benefit me                                                                  |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **Guidelines make me feel confident [@sharpOnlineSurveySTROBE2020]**                                                                                                                                                                                                                    | I use guidelines because of other people                                               |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **Guidelines help me develop as a researcher [@burfordTestingPRISMAEquity20122013; @sharpOnlineSurveySTROBE2020]**                                                                                                                                                                     | Guidelines benefit others                                                              |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| Guidelines may help me improve my manuscript [@burfordTestingPRISMAEquity20122013; @daviesSQUIREGuidelinesEvaluation2015; @deweyImpactPerceivedValue2019; @eysenbachg.CONSORTEHEALTHImplementationChecklist2013; @sharpOnlineSurveySTROBE2020]                                      | **Some benefits are more important than others**                                       |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| I believe guidelines may help me publish more easily [@svensoyQualitativeStudyResearchers2021]                                                                                                                                                                                          |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| I may use guidelines because journals and editors tell me to [@burfordTestingPRISMAEquity20122013; @fullerWhatAffectsAuthors2015; @sharpOnlineSurveySTROBE2020; @svensoyQualitativeStudyResearchers2021]                                                                             |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| I may use guidelines because other researchers expect it [@fullerWhatAffectsAuthors2015; @svensoyQualitativeStudyResearchers2021]                                                                                                                                                      |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| Standardized reporting benefits the community [@pagePRISMA2020Statement2021; @sharpOnlineSurveySTROBE2020; @svensoyQualitativeStudyResearchers2021]                                                                                                                                   |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **Immediate benefits are more important than hypothetical ones [@sharpOnlineSurveySTROBE2020; @svensoyQualitativeStudyResearchers2021]**                                                                                                                                               |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **Personal benefits are more important than benefits to others [@svensoyQualitativeStudyResearchers2021]**                                                                                                                                                                              |                                                                                        |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| I use reporting guidelines for planning research [@daviesSQUIREGuidelinesEvaluation2015; @sharpOnlineSurveySTROBE2020]                                                                                                                                                                 | Researchers use reporting guidelines for different tasks                               |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| I use reporting guidelines for designing research [@deweyImpactPerceivedValue2019; @pradyAssessingUtilityStandards2007; @pragerBarriersReportingGuideline2021; @sharpOnlineSurveySTROBE2020]                                                                                         | **I want guidance presented in formats that are better suited to the task I am doing** |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| I use reporting guidelines for writing [@daviesSQUIREGuidelinesEvaluation2015; @deweyImpactPerceivedValue2019; @pradyAssessingUtilityStandards2007; @sharpOnlineSurveySTROBE2020]                                                                                                    |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| I use reporting guidelines for checking my own or other people's writing [@pragerBarriersReportingGuideline2021; @sharpOnlineSurveySTROBE2020]                                                                                                                                         |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| I use reporting guidelines to appraise the quality of other people's reporting [@korevaarUpdatingStandardsReporting2016]                                                                                                                                                                |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| I use reporting guidelines for peer reviewing [@sharpOnlineSurveySTROBE2020]                                                                                                                                                                                                            |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I want items presented in the order in which I must do them [[CSL STYLE ERROR: reference with no printed form.]; @pagePRISMA2020Statement2021; @devriesProtocolFormatPreparation2015]**                                                                                           |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I want design or methods advice [@daviesSQUIREGuidelinesEvaluation2015; @pageUpdatingGuidanceReporting2021; @sharpOnlineSurveySTROBE2020]**                                                                                                                                         |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I want templates for writing [@deweyImpactPerceivedValue2019]**                                                                                                                                                                                                                       |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I want checklists that are easy to fill in [@macleodMDARMaterialsDesign2021; @struthersGoodReportsDevelopingWebsite2021]**                                                                                                                                                           |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I want checklists embedded into journal submission workflows [@deweyImpactPerceivedValue2019]**                                                                                                                                                                                       |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I want items embedded into data collection tools [@burfordTestingPRISMAEquity20122013]**                                                                                                                                                                                              |                                                                                        |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| Guidelines take time to read, understand and apply [@burfordTestingPRISMAEquity20122013; @fullerWhatAffectsAuthors2015; @svensoyQualitativeStudyResearchers2021]                                                                                                                      | Guidelines take time                                                                   |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| Some items require extra work which takes time and effort [@daviesFindingsNovelApproach2016; @daviesSQUIREGuidelinesEvaluation2015; @radert.MethodsDocumentingSystematic2014]                                                                                                         | **Itemization may decrease costs**                                                     |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I want an indication of which items to prioritize [@daviesSQUIREGuidelinesEvaluation2015; @pradyAssessingUtilityStandards2007]**                                                                                                                                                     | **Itemization may increase perceived costs**                                           |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| *Perceived complexity [@daviesSQUIREGuidelinesEvaluation2015; @deweyImpactPerceivedValue2019; @macleodMDARMaterialsDesign2021; @svensoyQualitativeStudyResearchers2021]*                                                                                                             | **I think guidelines make my manuscripts long and bloated**                            |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| *Long guidelines are off-putting [@burfordTestingPRISMAEquity20122013; @eysenbachg.CONSORTEHEALTHImplementationChecklist2013; @sharpOnlineSurveySTROBE2020; @struthersGoodReportsDevelopingWebsite2021]*                                                                             | **The benefits of using a reporting guideline may not outweigh the costs**             |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| ***Itemization helps me navigate guidance[@pageUpdatingGuidanceReporting2021]***                                                                                                                                                                                                        | The balance of benefits vs costs may be more favourable when guidelines are used early |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| ***Itemization summarizes the guidance[@deweyImpactPerceivedValue2019]***                                                                                                                                                                                                               |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| ***Itemization makes guidance appear longer[@pageUpdatingGuidanceReporting2021]***                                                                                                                                                                                                      |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| ***Itemization blocks the bigger picture[@daviesSQUIREGuidelinesEvaluation2015]***                                                                                                                                                                                                      |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **Following reporting guidance can result in long, bloated articles [@burfordTestingPRISMAEquity20122013; @daviesSQUIREGuidelinesEvaluation2015; @eysenbachg.CONSORTEHEALTHImplementationChecklist2013; @pradyAssessingUtilityStandards2007]**                                       |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **Long, bloated articles may exceed journal word limits [@eysenbachg.CONSORTEHEALTHImplementationChecklist2013; @fullerWhatAffectsAuthors2015; @macleodMDARMaterialsDesign2021; @pradyAssessingUtilityStandards2007]**                                                               |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I want options for where to report this item** [@daviesFindingsNovelApproach2016; @daviesSQUIREGuidelinesEvaluation2015; @eysenbachg.CONSORTEHEALTHImplementationChecklist2013; @fullerWhatAffectsAuthors2015; @pageUpdatingGuidanceReporting2021; @sharpOnlineSurveySTROBE2020] |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| ***The benefits of using a reporting guideline may not outweigh the costs [@eysenbachg.CONSORTEHEALTHImplementationChecklist2013; @fullerWhatAffectsAuthors2015; @sharpOnlineSurveySTROBE2020]***                                                                                     |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| Guidelines are more valuable when used early [@daviesSQUIREGuidelinesEvaluation2015; @deweyImpactPerceivedValue2019; @sharpOnlineSurveySTROBE2020; @struthersGoodReportsDevelopingWebsite2021]                                                                                       |                                                                                        |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| **I would clarify this item [@pageUpdatingGuidanceReporting2021; @pradyAssessingUtilityStandards2007]**                                                                                                                                                                                | **I think the guidance could be improved**                                             |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I would move this item [@daviesFindingsNovelApproach2016; @daviesSQUIREGuidelinesEvaluation2015]**                                                                                                                                                                                   | **Guidelines need to be kept updated**                                                 |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I would split this item into two** [@daviesSQUIREGuidelinesEvaluation2015; @pageUpdatingGuidanceReporting2021; @devriesProtocolFormatPreparation2015]                                                                                                                               |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I would add or remove items from this guideline** [@daviesSQUIREGuidelinesEvaluation2015; @korevaarUpdatingStandardsReporting2016; @pageUpdatingGuidanceReporting2021; @pradyAssessingUtilityStandards2007]                                                                        |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I would add or remove requirements from this item [[CSL STYLE ERROR: reference with no printed form.]; @pageUpdatingGuidanceReporting2021; @pradyAssessingUtilityStandards2007; @sharpOnlineSurveySTROBE2020; @tamPerceptionPreferredReporting2019]**                           |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **Guidelines can become out of date [@daviesSQUIREGuidelinesEvaluation2015]**                                                                                                                                                                                                           |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **Guidelines need to be updated [@pageUpdatingGuidanceReporting2021]**                                                                                                                                                                                                                  |                                                                                        |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| **I cannot report this because I didn't do it**                                                                                                                                                                                                                                           | **I feel unable to report this**                                                       |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **[@daviesSQUIREGuidelinesEvaluation2015; @eysenbachg.CONSORTEHEALTHImplementationChecklist2013; @pageUpdatingGuidanceReporting2021; @pradyAssessingUtilityStandards2007]**                                                                                                          | **I feel nervous or uncertain if I am unable to report an item**                       |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I cannot report this because of intellectual property issues**                                                                                                                                                                                                                          |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **[@eysenbachg.CONSORTEHEALTHImplementationChecklist2013]**                                                                                                                                                                                                                             |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I cannot report this because it clashes with journal guidelines [@pageUpdatingGuidanceReporting2021]**                                                                                                                                                                                |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I cannot report this because data was missing from my primary studies [@burfordTestingPRISMAEquity20122013]**                                                                                                                                                                         |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **Editors, reviewers or co-authors asked me to remove this item [@pradyAssessingUtilityStandards2007; @radert.MethodsDocumentingSystematic2014]**                                                                                                                                      |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I feel uncertain because I don't know how to say that I didn't do it [@pageUpdatingGuidanceReporting2021]**                                                                                                                                                                           |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I feel worried that I will be judged for transparently reporting something I didn't do [@pageUpdatingGuidanceReporting2021; @sharpOnlineSurveySTROBE2020]**                                                                                                                          |                                                                                        |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| I may not know that reporting guidelines exist [@deweyImpactPerceivedValue2019; @fullerWhatAffectsAuthors2015; @korevaarUpdatingStandardsReporting2016; @struthersGoodReportsDevelopingWebsite2021; @svensoyQualitativeStudyResearchers2021]                                        | I can only use what I know about and have                                              |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| I may not be able to easily access guidance [@struthersGoodReportsDevelopingWebsite2021; @svensoyQualitativeStudyResearchers2021]                                                                                                                                                      |                                                                                        |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| **Reporting guidelines may be less valuable to experienced researchers [@deweyImpactPerceivedValue2019; @eysenbachg.CONSORTEHEALTHImplementationChecklist2013; @sharpOnlineSurveySTROBE2020]**                                                                                        | **Reporting guidelines are more valuable to inexperienced researchers**                |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **Experienced researchers feel that they already know how to report [@daviesSQUIREGuidelinesEvaluation2015; @deweyImpactPerceivedValue2019; @sharpOnlineSurveySTROBE2020]**                                                                                                           | **Reporting guidelines can be hard to use at first but get easier with experience**    |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **Experienced researchers find guidance patronizing and feel untrusted [@eysenbachg.CONSORTEHEALTHImplementationChecklist2013; @fullerWhatAffectsAuthors2015; @macleodMDARMaterialsDesign2021; @pageUpdatingGuidanceReporting2021]**                                                 |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **Reporting guidelines can be hard to use at first but get easier with experience [@daviesSQUIREGuidelinesEvaluation2015; @fullerWhatAffectsAuthors2015; @svensoyQualitativeStudyResearchers2021]**                                                                                   |                                                                                        |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| **I want design or methodological advice [@macleodMDARMaterialsDesign2021; @pageUpdatingGuidanceReporting2021; @sharpOnlineSurveySTROBE2020]**                                                                                                                                        | **I want or need design advice**                                                       |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I don't know how to do this item [@daviesSQUIREGuidelinesEvaluation2015; @pageUpdatingGuidanceReporting2021; @pradyAssessingUtilityStandards2007]**                                                                                                                                 | **I think this guidance prescribes how research should be designed**                   |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **Guidelines are procedural straightjackets [@sharpOnlineSurveySTROBE2020]**                                                                                                                                                                                                            |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **This guideline is too prescriptive [@pageUpdatingGuidanceReporting2021; @sharpOnlineSurveySTROBE2020; @tamPerceptionPreferredReporting2019]**                                                                                                                                       |                                                                                        |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| *The guideline's applicability criteria are not clear [@deweyImpactPerceivedValue2019; @korevaarUpdatingStandardsReporting2016; @struthersGoodReportsDevelopingWebsite2021]*                                                                                                          | A guideline's scope can be unclear                                                     |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| *This guideline isn't a perfect fit for me [@struthersGoodReportsDevelopingWebsite2021]*                                                                                                                                                                                                | A guideline can be too narrow                                                          |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **This guideline doesn't generalise [@deweyImpactPerceivedValue2019; @macleodMDARMaterialsDesign2021; @pageUpdatingGuidanceReporting2021; @sharpOnlineSurveySTROBE2020; @tamPerceptionPreferredReporting2019]**                                                                     | A guideline's scope can be too broad                                                   |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **This guideline is too prescriptive [@pageUpdatingGuidanceReporting2021; @sharpOnlineSurveySTROBE2020; @tamPerceptionPreferredReporting2019]**                                                                                                                                       |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I don't want to see optional items that only apply to other types of study [@pradyAssessingUtilityStandards2007; @struthersGoodReportsDevelopingWebsite2021]**                                                                                                                       |                                                                                        |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| **I need to adhere to journal guidelines or other research guidelines [@deweyImpactPerceivedValue2019; @fullerWhatAffectsAuthors2015; @pageUpdatingGuidanceReporting2021; @pradyAssessingUtilityStandards2007]**                                                                     | Authors often need to adhere to multiple sets of guidance                              |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I might need to use multiple reporting guidelines [@sharpOnlineSurveySTROBE2020]**                                                                                                                                                                                                    | I want guidelines to harmonize                                                         |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I want reporting guidelines to be linked or embedded [@korevaarUpdatingStandardsReporting2016; @pageUpdatingGuidanceReporting2021]**                                                                                                                                                 |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I want reporting guidelines to use similar structure [@pageUpdatingGuidanceReporting2021]**                                                                                                                                                                                           |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I want reporting guidelines to use similar terms [@pageUpdatingGuidanceReporting2021]**                                                                                                                                                                                               |                                                                                        |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| **I don't like checklists[@deweyImpactPerceivedValue2019; @eysenbachg.CONSORTEHEALTHImplementationChecklist2013; @sharpOnlineSurveySTROBE2020; @struthersGoodReportsDevelopingWebsite2021]**                                                                                         | I experience reporting guidelines primarily as, or through, checklists                 |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I may use the checklist instead of the full guidance [[CSL STYLE ERROR: reference with no printed form.]]**                                                                                                                                                                         |                                                                                        |
|                                                                                                                                                                                                                                                                                           |                                                                                        |
| **I may use the checklist before I read the full guidance [[CSL STYLE ERROR: reference with no printed form.]]**                                                                                                                                                                      |                                                                                        |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+

: Codes and descriptive themes identified from a qualitative evidence synthesis. Items in bold did not appear in the quantitative questions. Items in italic offer possible explanations to some quantitative findings. {#tbl-codes-from-qual}
