---
shift-heading-levels-by: 1
---

## Boxes

### Box. Item before {#sec-box-item-b4}

Limitations of individual reporting items (as described in guideline publications) include:

* Multiple subitems hidden within blocks of text
* lengthy explanation of development
* Design advice or discussion of why particular design choices are good or bad
* Lack of consistent structure, or any structure at all
* Superfluous information masks the actual reporting instructions, and makes the item appear very long.
* No explanation of who needs the information and why
* Text can be unnecessarily long, and passive voice makes it even longer
* Lack of reassuring tone, or encouragement to explain unusual choices
* It's not always clear when an item (or sub item) does or does not apply
* Items may not link to other useful resources
* Items may make assumptions about design choices and not explain what to write if something was not, or could not be done.
* Not all items include examples of reporting


### Box. Item {#sec-box-item}

Redesigned reporting items include the following intervention changes:

* Reporting instructions are the only content that is immediately viewable. All other information is hidden until an expandable box is clicked
* Items follow a consistent structure
* Text is shortened and simplified by:
    * using active voice and consistent phrasing and sentence structure
    * defining words in a glossary, so definitions appear when a word is clicked
    * separating notes / context and placing it within the expandable box
* Subitems are clearly separated
* Instruction on what to write if something was not, or could not be done.
* Reassuring quotes
* Instruction on when an item (or sub item) applies
* Explanation about why a reader needs this information
* Links to other resources and training
* All items include examples

### Box. FAQ {#sec-box-FAQ}