## Appendix {{< var appendix.workshop_step_4 >}}: Step 4: Identifying what needs to change {.unnumbered}

Instructions @michieBehaviourChangeWheel2014 :

*When it comes to an individual/group/population doing/not doing X, use evidence and theory to form a judgement about which of the following needs to change and in each case whether it should be targeted directly or through one of the other elements of the COM-B system. Note that it might be appropriate to apply this analysis to one of more supportive or competing behaviours.*

+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **The individual/group/population would have to…** |                                                                                                                                                                                            |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **CAPABILITY**                                     |                                                                                                                                                                                            |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Know more about why it was important               | e.g., better understand the benefits of stopping smoking                                                                                                                                   |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Know the importance of research waste PL                                                                                                                                               |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Understand the benefits of clearly reporting (to themselves and the community). These might include smoother review, citations, makes their work more useful to the community. JdB, SK |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Authors need to know why items are important and who they are important to JH                                                                                                          |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Understand how a RG can help them with their personal goals                                                                                                                            |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Know more about how to do it                       | e.g., better understand effective ways to lose weight                                                                                                                                      |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Know that guidance exists PL, JH                                                                                                                                                       |
|                                                    |                                                                                                                                                                                            |
|                                                    | <!-- -->                                                                                                                                                                                   |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Better understanding of how to find guidance JdB,SK                                                                                                                                    |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Better understanding of how to use guidance JdB                                                                                                                                        |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Better understanding of how to use items to improve writing SK                                                                                                                         |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Need to know what to actually report, how to report it, and how to keep writing fluid and concise SK, JH                                                                               |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   How to report “imperfect” things                                                                                                                                                       |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Authors need to know where they can report items JH                                                                                                                                    |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Know the process of writing (maybe not requirement) JdB                                                                                                                                |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Understand how a team can use RGs in practice CS                                                                                                                                       |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Authors need to know what reporting guidance is, and how it is different to design guidance or design requirements                                                                     |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Authors need to know which guideline applies to their work, JH                                                                                                                         |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Authors need to know which guidelines exist, JH                                                                                                                                        |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Have better physical skills                        | e.g., learn how to operate machinery                                                                                                                                                       |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Have better mental skills                          | e.g., learn how to reason more effectively                                                                                                                                                 |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Be able to understand the guidance (language) PL                                                                                                                                       |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Be able to understand the guidance (conceptually) PL, SK, JH                                                                                                                           |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Have a good writing process (but maybe this isn’t a requirement) (JdB, JH) including time management CS                                                                                |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Know how to write/communicate clearly JdB, CS (could be delivered through training, games)                                                                                             |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Learning how to search for reporting guidance SK                                                                                                                                       |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Better knowledge of designs PL                                                                                                                                                         |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Have more physical strength                        | e.g., build up muscle for demanding physical work                                                                                                                                          |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Have more mental strength                          | e.g., develop stronger resilience against cravings                                                                                                                                         |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Knowing how to stand up to objections from co-authors, editors and peer reviewers JdB, CS                                                                                              |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Authors need to be open to new ways of working, or changes to the way they normally write/do their research SK                                                                         |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Overcome physical limitations                      | e.g., get around problems of stature or disability                                                                                                                                         |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Overcome mental obstacles                          | e.g., reduce unwanted urges or feelings                                                                                                                                                    |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Overcome the feeling that good reporting is too hard or not something I need to do. Not for me. JdB                                                                                    |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Overcome the feeling that RGs are an extra burden SK                                                                                                                                   |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Have more physical stamina                         | e.g., develop greater capacity to maintain physical effort                                                                                                                                 |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Have more mental stamina                           | e.g., develop greater capacity to maintain mental effort                                                                                                                                   |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Persisting with good reporting even if it feels like it takes longer, or in the face of objection from others. JdB, CS                                                                 |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Being dogged (persisting, keep on keeping on)                                                                                                                                          |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Authors need to know that it’s never too late (in your career) to make improvements in how to write. SK                                                                                |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **OPPORTUNITY**                                    |                                                                                                                                                                                            |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Have more time to do it                            | e.g., create dedicated time during the day                                                                                                                                                 |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Time management                                                                                                                                                                        |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Authors encounter guidance at the very end of the writing process which is when they have least time                                                                                   |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Authors need to ask for time for writing CS                                                                                                                                            |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Have more money                                    | e.g., be given or earn funds to support the behaviour                                                                                                                                      |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Budget for writing time and writing resources/help e.g., a publications coordinator, CS                                                                                                |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Have the necessary materials                       | e.g., acquire better tools for the job                                                                                                                                                     |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Translations PL                                                                                                                                                                        |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Have it more easily accessible                     | e.g., provide easier access to facilities                                                                                                                                                  |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Fixing broken links PL                                                                                                                                                                 |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Guidance is split between documents that aren’t linked                                                                                                                                 |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Examples are often separate to the checklists and hard to discover                                                                                                                     |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Guidance behind paywall                                                                                                                                                                |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Navigability of EQUATOR site, JH                                                                                                                                                       |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Guidance can be buried within development or E&E documents or in figures JH, JdB                                                                                                       |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Guidance should be in a usable format JdB, JH                                                                                                                                          |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Authors must have access to all the information about their own study JdB                                                                                                              |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Have more people around them doing it              | e.g., be part of a ‘crowd’ who are doing it                                                                                                                                                |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   For it to become a norm in their community JdB                                                                                                                                         |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Be aware that others are using guidelines – belonging to a crowd JH, PL                                                                                                                |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Have more triggers to prompt them                  | e.g., have more reminders at strategic times                                                                                                                                               |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Being reminded in the early stages of writing (e.g., text books, social, journal pages, funders, automated personal reminders after interacting with other services) JH, SK, JdB, CS   |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Have more support from others                      | e.g., have one’s family or friends behind one                                                                                                                                              |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Sometimes others can discourage use of guidelines JH                                                                                                                                   |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Having others (supervisors, librarians, editors, peer reviewers) support the behaviour JdB                                                                                             |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Someone to give support for each guideline CS                                                                                                                                          |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **MOTIVATION**                                     |                                                                                                                                                                                            |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Feel that they want to do it enough                | e.g., feel more of a sense of pleasure or satisfaction from doing it                                                                                                                       |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Felt like cumbersome reports JH                                                                                                                                                        |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Felt patronized JH                                                                                                                                                                     |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Felt like RGs are ‘design straitjackets’ JH                                                                                                                                            |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Felt afraid of reporting study limitations JH                                                                                                                                          |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Authors should believe that RGs will make their writing easier JdB, JH                                                                                                                 |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Believe that RGs will help with career progression, SK                                                                                                                                 |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Feel that they need to do it enough                | e.g., care more about the negative consequences of not doing it                                                                                                                            |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Felt like it’s the responsibility of the editor or reviewer JH                                                                                                                         |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   They should feel like it is their responsibility JdB                                                                                                                                   |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Believe that it would be a good thing to do        | e.g., have a stronger sense that one should do it                                                                                                                                          |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Even if an author understands why a RG is important, they still need care (could be addressed through modelling) JH                                                                    |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Give recognition or reward to authors for using RGs PL                                                                                                                                 |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Authors don’t think editors/reviewers use checklist info JH                                                                                                                            |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Develop better plans for doing it                  | e.g., have clearer and better developed plans for achieving it                                                                                                                             |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Have a plan for how and when they will use guidance JdB, JH                                                                                                                            |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Develop a habit of doing it                        | e.g., get into a pattern of doing it without having to think                                                                                                                               |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Need to have a habit of using guidance PL                                                                                                                                              |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Develop a habit that the first step of writing is to check for guidance                                                                                                                |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **OTHER**                                          |                                                                                                                                                                                            |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| (JH added): Have it easier to do                   | -   Guidance should be easier to understand JH, PL                                                                                                                                         |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Items are not prioritised. Often the first items are generic background items that seem patronising. JH                                                                                |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Making websites easier to use PL                                                                                                                                                       |
|                                                    |                                                                                                                                                                                            |
|                                                    | -   Simplification PL                                                                                                                                                                      |
+----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Workshop participants' ideas around what needs to change for authors to perform our target behaviour. Based on the COM-B questionnaire @michieBehaviourChangeWheel2014

<!--66 things that need to change-->