## Appendix {{< var appendix.workshop_step_6 >}}: Step 6: Identifying policy categories {.unnumbered}

Instructions @michieBehaviourChangeWheel2014:

*Use the APEASE criteria to identify appropriate policy categories based on the intervention functions identified in Step 5:*

-   *Affordability*
-   *Practicability*
-   *Effectiveness and cost-effectiveness*
-   *Acceptability*
-   *Side-effects/safety*
-   *Equity*

+----------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Policy Category (the methods for delivering the function/active ingredient)**  | **Definition**                                                                                     | **Example**                                                                                                                                                                                                                                 | **APEASE** \                                                                                                                                                                                                                                                                                                                               |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | **Affordability**                                                                                                                                                                                                                                                                                                                          |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | **Practicability**                                                                                                                                                                                                                                                                                                                         |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | **(Cost)-Effectiveness**                                                                                                                                                                                                                                                                                                                   |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | **Acceptability**                                                                                                                                                                                                                                                                                                                          |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | **Side-effects/safety**                                                                                                                                                                                                                                                                                                                    |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | **Equity**                                                                                                                                                                                                                                                                                                                                 |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
+----------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Communication/marketing**                                                      | Using print, electronic, telephonic or broadcast media                                             | Eg: Conducting mass media campaigns                                                                                                                                                                                                         | **Affordability:** some are and some aren’t affordable                                                                                                                                                                                                                                                                                     |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Newsletters                                                                                                                                                                                                                                 | **Practicability:** all practical and not difficult to do, except the chat                                                                                                                                                                                                                                                                 |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  | (using communication to educate,                                                                   | Adverts/posts on social media                                                                                                                                                                                                               | **(Cost)-Effectiveness:** it will be cost-effective if the right marketing professionals are available to help planning                                                                                                                                                                                                                    |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Newspaper articles?                                                                                                                                                                                                                         | **Acceptability:** there won’t be problems of acceptability                                                                                                                                                                                                                                                                                |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Blog posts                                                                                                                                                                                                                                  | **Side-effects/safety:** overload? (which can be prevented by proper planning)                                                                                                                                                                                                                                                             |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | People sharing their good practice                                                                                                                                                                                                          | **Equity:** equity can be good if targeting is adequately planned                                                                                                                                                                                                                                                                          |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Editorials in journals                                                                                                                                                                                                                      |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Articles in professional publications                                                                                                                                                                                                       |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Webinars                                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Hotline/chat function?                                                                                                                                                                                                                      |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
+----------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Guidelines**                                                                   | Creating documents that recommend or mandate practice. This includes changes to service provision  | Eg: Producing and disseminating treatment protocols.                                                                                                                                                                                        | **Affordability:** development of sets of rules required work hours; implementation is not a problem for cost (lawyers can cost a lot!) - it depends on who works                                                                                                                                                                          |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Recommendations for curricula (from accreditation orgs? To unis?)                                                                                                                                                                           | **Practicability:** not difficult to write new rules/guidance, especially when using existing frameworks                                                                                                                                                                                                                                   |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Research organisations telling their staff what they recommend                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Funders recommending good reporting practice                                                                                                                                                                                                | **(Cost)-Effectiveness:** cost-effectiveness depends on whether the guidance is actually used, which is likely to require some form of enforcement (someone to check). There is also a cost to folks using guidance, as takes time – is that time commitment giving them something?                                                        |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Guidance for publishers on how to use RGs                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Updated instructions for authors (from publishers/journals to authors)                                                                                                                                                                      | **Acceptability:** possibly low, if things are rules that researchers HAVE to follow – might feel dictated to. Acceptability possibly dependent on who produces the guidance – some researchers are looking for help and might appreciate                                                                                                  |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Guidance for authors                                                                                                                                                                                                                        |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Guidance for guideline developers                                                                                                                                                                                                           | **Side-effects/safety:** researchers exodus, when talking about dictated rules?                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | **Equity:** independent researchers (who don’t get institutional support) will have problems.                                                                                                                                                                                                                                              |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | Language that guidance is available in. Accessibility of guidance.                                                                                                                                                                                                                                                                         |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
+----------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Fiscal measures**                                                              | Using the tax system to reduce or increase the financial cost                                      | Eg: Increasing duty or increasing anti-smuggling activities                                                                                                                                                                                 | **Affordability:** Would cost publishers / funders a great deal. But the measures proposed increase the affordability of good reporting for authors.                                                                                                                                                                                       |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | **Practicability:** difficult because it requires additional checks. Publisher/funder has to make a judgement of good reporting, which might be challenging, particularly when guidance isn’t clear.                                                                                                                                       |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Changing APCs for good/bad reporting                                                                                                                                                                                                        | **(Cost)-Effectiveness:**                                                                                                                                                                                                                                                                                                                  |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Funders adding incentives (more money for good reporting, less money for poor reporting, funding being conditional on good reporting)                                                                                                       |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | **Acceptability:** Publishers might not like having to do more work. Authors already struggle with reporting – can see push back particularly from those who are judged negatively.                                                                                                                                                        |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | **Side-effects/safety:** Bias when publishers/funders judge reporting quality                                                                                                                                                                                                                                                              |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | **Equity:** Issues around who can access and use the guidance, who gets support and education. to report well.                                                                                                                                                                                                                             |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
+----------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Legislation**                                                                  | Making or changing laws                                                                            | Eg: Prohibiting sale or use                                                                                                                                                                                                                 | **Affordability:** Publishers’ policies: cheap for us, some campaigning needed. Could be less affordable for publishers, if they lose authors or if they need to enforce.                                                                                                                                                                  |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Publishers/journals refusing to publish poorly reported articles                                                                                                                                                                            | ‘Research police’: expensive: lots of campaigning, development, etc.                                                                                                                                                                                                                                                                       |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Publishers require that their journals must enforce RG use                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Legislation requiring journals/publishers to use reporting standards (research police)                                                                                                                                                      | **Practicability:** ‘Research police’: impractical, a lot of work, difficult to do. Publishers: we have existing relationships to lean on, difficult but plausible. A lot of time, money, knowledge for publishers to check RG use – high barrier? If authors find RGs difficult to use, why would publishers be any different?            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Mandating that funders use reporting quality of protocols as a condition for funding (eg, UKRI **could** make this a condition of the way MRC etc gives out funding; could be done via wider orgs, such as the way the EU has mandated OA)  |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | **(Cost)-Effectiveness:** Unsure, but feeling is that it would be a lot of work for potentially little gain, potentially much gain, depending on whether things worked and whether enforcement was done or not.                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | **Acceptability:** Researcher pushback? Publisher pushback?                                                                                                                                                                                                                                                                                |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | **Side-effects/safety:** Authors might avoid publishers/funders that mandate RGs.                                                                                                                                                                                                                                                          |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | **Equity:** Authors from lower resource areas could be negatively affected – it isn’t fair to be penalised if they haven’t had education / unable to access guidance (due to copyright).                                                                                                                                                   |
+----------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Environmental/social planning**                                                | Designing and/or controlling the physical or social environment                                    | Adding Q&As and forums to the EQUATOR website / RG websites                                                                                                                                                                                 | **Affordability:** Some of affordable, and are scalable (can make a few small changes at a time). Journal submission system changes could expensive for publishers.                                                                                                                                                                        |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Improving the design of the EQUATOR website / RG websites to make them easier to use                                                                                                                                                        |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Changing journal submission systems                                                                                                                                                                                                         | **Practicability:** Many of these are practical for us and RG developers.  Journal submission systems are trickier though.                                                                                                                                                                                                                 |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Posters/reminders in physical environments where researchers are (e.g. universities, hospitals)                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | **(Cost)-Effectiveness:** small change, big impact for many of these. Reporting clinics could be less cost effective, as reaching fewer people.                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | **Acceptability:** RG developers likely to be happy with us making these changes or recommendations, as close relationships. Researchers likely to really like these options, as often looking for help and guidance                                                                                                                       |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | **Side-effects/safety:** Potentially overwhelming for us                                                                                                                                                                                                                                                                                   |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | **Equity:** Time zones, languages,                                                                                                                                                                                                                                                                                                         |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
+----------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Service provision**                                                            | Helpline: somewhere that people can come and get help from                                         | Training, eg Pubschool, in person, MOOC,                                                                                                                                                                                                    | **Affordability:** Depends on the service, but many would be less affordable for EQUATOR: lots of time to reach only a small number of people.                                                                                                                                                                                             |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  | Delivering training                                                                                | Interactive chat                                                                                                                                                                                                                            | Could be something that we provide commercially.                                                                                                                                                                                                                                                                                           |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  | Could be things offered by us, by institutions, by journals, by third parties                      | ‘Reporting clinics’ where people can get help                                                                                                                                                                                               | Could be an affordable way for funders / journals / universities to provide help, meeting their research integrity requirements                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | University’s own ‘reporting guideline help space’                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Writing centres, publication officers                                                                                                                                                                                                       | **Practicability:** For EQUATOR, a lot of time required. Possibly not practical unless could get specific funding for it. Services offered by funders / journals / universities: could be sensible at scale, but could also mean that the specific support we think about would be lost in the generic support that everyone would need.   |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Third-party services, like a reporting quality check from a company                                                                                                                                                                         |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Funders offering help to their recipients.                                                                                                                                                                                                  | **(Cost)-Effectiveness:** Depends on the amount of benefit to providing organisation. If automated, could be a very cost-effective option.                                                                                                                                                                                                 |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Sponsors offering help to their sponsorees’ research                                                                                                                                                                                        |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Journals offering help to their authors                                                                                                                                                                                                     | **Acceptability:** Researchers appreciate offered help, but they need to know it exists and that it is helpful. Danger that it could be seen as another red tape thing to get through when designing research. Depends on the format of the help – is it timeous, actionable, how much work does it make for the researchers?              |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    | Universities offering help to their members                                                                                                                                                                                                 |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | **Side-effects/safety:** Would need to be effective help / to a quality standard to ensure researchers aren’t negatively affected by the help. Eventually the only people using it would be junior / new researchers. Would need to be clear that the help doesn’t mean a guarantee of publication / don’t mislead                         |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             | **Equity:** If a paid service, then not equitable. If by funder / sponsor, then only people connected to more wealthy funders / sponsors would be benefit                                                                                                                                                                                  |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
|                                                                                  |                                                                                                    |                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                            |
+----------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Workshop participants' considerations on the affordability, practicability, effectiveness and cost-effectiveness, acceptability, side-effects/safety, and equitability of policy categories. Policy categories and their definitions come from @michieBehaviourChangeWheel2014.

**Favourite policy routes:** 

CS: Environmental  

JH: Environmental first. Once environmental is better, then can look at guidelines – we’re swimming in guidelines now. Service provision after guidelines and comms, due to scalability 

JdB: Environmental first; once it is done, then we can share with communication and guidelines and service provision 

PL: Environmental first and then guidelines and communication – they need each other to work 

SK: Environmental and communication more easily changed by us 

Consensus: legislation and fiscal would be more acceptable once environmental, communication, and guidelines are done ‘right’, not fair here yet