## BCW Step 7 – Identifying possible changes {.appendix}

#TODO this table is incomplete and needs replacing with the initial table from the focus groups.

The original instructions @michieBehaviourChangeWheel2014 were to:

*Use the APEASE criteria to identify appropriate \[Behaviour Change Techniques\] based on the intervention functions identified in Step 5*.

Because EQUATOR members were not familiar with behaviour change techniques I performed this step on my own and instead I asked EQUATOR members to brainstorm intervention changes to address "what needs to change" items from step 4 by considering each intervention function in turn.

\newpage

\blandscape

+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Influence                                                                                                                                                                                        | Ideas                                                                                                                                                                                                                                                                             |
+==================================================================================================================================================================================================+===================================================================================================================================================================================================================================================================================+
| Authors may not know what reporting guidance is, or whether it is different to design guidance                                                                                                   | -   State what reporting guidelines are on the EQUATOR & GoodReports.org landing pages                                                                                                                                                                                            |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  | ```{=html}                                                                                                                                                                                                                                                                        |
|                                                                                                                                                                                                  | <!-- -->                                                                                                                                                                                                                                                                          |
|                                                                                                                                                                                                  | ```                                                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                  | -   For each guideline, state its aim at the top of all tools / guidance documents                                                                                                                                                                                                |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Authors may not understand the guidance                                                                                                                                                          | -   Define key words or terms in a glossary or tooltips                                                                                                                                                                                                                           |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 1.  Authors may not understand concepts, terms or words within the guidance, or they may understand them differently to how the developers intended – E, S                                       | -   Provide training courses                                                                                                                                                                                                                                                      |
| 2.  Authors may have nowhere to turn for help should they not understand something                                                                                                               |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  | -   Allow authors to give user feedback and ask questions                                                                                                                                                                                                                         |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  | -   Update guidance in response to user feedback to clarify confusing terms                                                                                                                                                                                                       |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  | -   Provide examples of good and bad reporting as authors report that examples help them understand what the guidance means                                                                                                                                                       |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Authors may not know why a reporting item is important, or who it is important to                                                                                                                | For each item, clearly state why it is important and who it is important to.                                                                                                                                                                                                      |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Authors may not understand how to report a particular item in practice                                                                                                                           | -   Provide examples of good reporting in different contexts                                                                                                                                                                                                                      |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  | -   Provide examples of imperfect reporting and how it could be improved                                                                                                                                                                                                          |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Authors may feel concerned if they are unable to report an item                                                                                                                                  | -   Provide examples of perfectly reported “imperfect” elements                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 1.  Authors may not know how to report something that they didn’t (or couldn’t) do, which may leave them feeling uncertain or afraid to be transparent                                           | -   Acknowledge that all studies have limitations                                                                                                                                                                                                                                 |
| 2.  This is more likely to happen if author encounters guidance late                                                                                                                             |                                                                                                                                                                                                                                                                                   |
| 3.  If an author doesn’t know how to do something (e.g., a sample size calculation) then they cannot report it                                                                                   | -   Acknowledge that researchers may have justifications for not doing something                                                                                                                                                                                                  |
| 4.  Authors may not be able to report an item because of external reasons (e.g., IP, or data was missing from primary studies)                                                                   |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  | -   Provide quotes from editors emphasising that transparency is more important than perfection                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  | -    Instead of demonising bad design choices remain neutral and encourage transparency, but link to resources where researchers can learn and make their next study better                                                                                                       |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Following a guideline can result in lengthy, bloated reports                                                                                                                                     | -   Provide examples of concise reporting                                                                                                                                                                                                                                         |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 1.  Authors may not know how to keep writing fluid and concise without letting the manuscript bloat – E, S                                                                                       | -   Give authors options of where an item can be reported. E.g., If the item is only useful to a subset of readers, perhaps it can go in an appendix / supplement.                                                                                                                |
| 2.  Authors may be constrained by journal word limits                                                                                                                                            |                                                                                                                                                                                                                                                                                   |
| 3.  Authors may not know *where* they can report an item, e.g., what section, in the text or in a table or figure, in the manuscript or in supplementary material – E                            | -   Provide alternative reporting methods, e.g., PRISMA flow diagram or details in tables                                                                                                                                                                                         |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Authors may not understand the benefits of reporting guidelines                                                                                                                                  | -   Make the benefits of using a reporting guideline clear by adding a value statement to journal guidelines, the EQUATOR Network site, guideline sites, the checklist & guidance (all touch points)                                                                              |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 1.  Authors report caring more about personal, immediate benefits compared to hypothetical benefits to others - S                                                                                | -   Create new rewards for authors e.g., badges on published articles or a certificate after completing training                                                                                                                                                                  |
| 2.  Authors report wanting to feel confident, be better at their job and do their job more quickly. Authors may not expect reporting guidelines to help them achieve these personal goals – E, S |                                                                                                                                                                                                                                                                                   |
| 3.  Authors may not understand that using a reporting guideline will help them publish – S                                                                                                       | -   Provide statistics about acceptance rates of articles that follow / don’t follow reporting standards                                                                                                                                                                          |
| 4.  Authors may not understand how transparent reporting helps research consumers, or why poor reporting leads to waste – E, S                                                                   |                                                                                                                                                                                                                                                                                   |
| 5.  Even if authors do understand about research waste they may not care                                                                                                                         |                                                                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Authors may not believe reported benefits of using a RG                                                                                                                                          | Provide quotes from editors or reviewers emphasising their preference for transparent reporting                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 1.     Authors may not believe that editors or reviewers care about reporting checklists                                                                                                         |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| May not believe that a complete checklist will help them get published                                                                                                                           |                                                                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Authors use reporting guidelines for different tasks and want tools to make that job easier. These tasks include:                                                                                | Instruct authors on how and when to use guidelines                                                                                                                                                                                                                                |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 1.     Planning research                                                                                                                                                                         | Provide training courses                                                                                                                                                                                                                                                          |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| a.     Authors want items presented in the order in which decisions need to be made                                                                                                              | Interactive forms as writing tools (e.g. COBWEB)                                                                                                                                                                                                                                  |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 2.     Designing research                                                                                                                                                                        | Templates for drafting                                                                                                                                                                                                                                                            |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| a.     Authors want items presented in the order in which decisions need to be made                                                                                                              | Add guidance to reviewers e.g.,                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| b.     Authors want links to resources                                                                                                                                                           | provide terms they can search for with CTRL-F                                                                                                                                                                                                                                     |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 3.     Whilst collecting data                                                                                                                                                                    | Include extra guidance for reviewers, e.g., see JARS which explains to reviewers why an author may make certain choices                                                                                                                                                           |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| a.     Authors want items ordered in the order they are done                                                                                                                                     | Provide suggested text that a reviewer can use to request additional information                                                                                                                                                                                                  |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| b.     Items embedded into data collection tools                                                                                                                                                 | Build a reviewing tool that generates a report with instructions to authors                                                                                                                                                                                                       |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 4.     Drafting manuscript                                                                                                                                                                       | Tools for co-authors to check each other’s work                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| a.     templates                                                                                                                                                                                 | Suggest that primary authors ask their co-authors to check their reporting                                                                                                                                                                                                        |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 5.     Checking manuscripts                                                                                                                                                                      | Provide separate user journeys on EQUATOR website to guide researchers towards the tool that will help with the job they are doing                                                                                                                                                |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 6.     Demonstrating compliance                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| a.     Checklists embedded into submission workflows                                                                                                                                             |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 7.     Reviewing the reporting of other people’s manuscripts                                                                                                                                     |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 8.     Appraising the quality of other people’s manuscripts                                                                                                                                      |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 9.     Authors may not initially know *when* they are supposed to use a reporting guideline                                                                                                      |                                                                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Authors may not be aware of which reporting guidelines exist                                                                                                                                     | Have champions within universities at an accessible level (e.g. post-doc), someone that ECRs feel comfortable talking with, perhaps EQUATOR Ambassadors e.g. as part of the UKRN                                                                                                  |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 1.     Authors may have never heard of reporting guidelines – E, S                                                                                                                               | Advertise guidelines through professional societies and conferences                                                                                                                                                                                                               |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 2.     Authors may not know what guidance exists – E, S                                                                                                                                          | Create horizontal links between related guidelines on EQUATOR site and within the guideline documents & tools                                                                                                                                                                     |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 3.     Authors may not know how to search for reporting guidelines – E                                                                                                                           | Make EQUATOR’s search tool more prominent and easier to use                                                                                                                                                                                                                       |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 4.     Most guidelines on the EQUATOR site are hardly ever accessed                                                                                                                              | Encourage more journals to endorse guidelines                                                                                                                                                                                                                                     |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Authors may struggle to identify which guidance applies to them                                                                                                                                  | Clearly state what kind of research the guidance applies to                                                                                                                                                                                                                       |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 1.     Authors may not know what guidance applies to their work – E, S                                                                                                                           | Include IF… THEN… rules to forward authors to more appropriate guidance (e.g. “If you are doing X, use Y instead of this guideline”)                                                                                                                                              |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 2.     Authors may not realise that more specific guidance exists – E                                                                                                                            | If no better guideline exists then warn the user that they can still use this guideline but that they may need to ignore certain questions e.g., “this guideline is for studies that did X. You can still use it if  you did Y, but you will need to ignore items 4, 6, and 8”).  |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 3.     Authors may not understand about different study designs, making it difficult for them to identify which guidance  - E                                                                    | A game where you start with a research question and manipulate methodological variables to arrive at the correct study design and, therefore, reporting guideline                                                                                                                 |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 4.     An author’s “perfect fit” guideline may not exist                                                                                                                                         |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 5.     Authors may not understand whether a guideline includes optional items, or whether a particular item applies to them                                                                      |                                                                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Authors may struggle to access guidance                                                                                                                                                          | Ensure guidance is open access                                                                                                                                                                                                                                                    |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 1.     Authors may not be able to navigate the EQUATOR Network website                                                                                                                           | Ensure all of a guideline’s resources link to one another (e.g. checklists link to E&Es, ideally item by item).                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 2.     Authors may not be able to access paywalled journal articles                                                                                                                              | Ensure all tools are in ready-to-use formats                                                                                                                                                                                                                                      |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 3.     Journal websites can feature broken links                                                                                                                                                 | Fix broken links                                                                                                                                                                                                                                                                  |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 4.     Researchers may encounter the checklists but never discover or read the explanation & elaboration document. – S                                                                           | Make EQUATOR’s website easier to navigate                                                                                                                                                                                                                                         |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 5.     Researchers may never discover examples if they are separate to the main guidance or checklist                                                                                            |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 6.     Guidance can be buried within a longer development article                                                                                                                                |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 7.     Checklists can be published as PDF tables that cannot be copied or completed                                                                                                              |                                                                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Authors use the checklists and E&E differently                                                                                                                                                   | Ensure checklists and E&Es are linked, ideally item by item                                                                                                                                                                                                                       |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 1.     Many authors will only ever use the checklist. Sometimes this is purposeful, but other times it may be because authors don’t know that an E&E exists.                                     |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 2.     Some will read the E&E fully, but many will dip in and out whilst using the checklist                                                                                                     |                                                                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Using a reporting guideline has costs                                                                                                                                                            |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 1.     Guidelines and checklists take time to find, read and understand                                                                                                                          |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 2.     Authors may underestimate the time required for writing                                                                                                                                   |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 3.     Guidelines and checklists require work to apply. Sometimes this work requires input from multiple people.                                                                                 |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 4.     Authors want to know which items to prioritize                                                                                                                                            |                                                                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Authors may need more time to write                                                                                                                                                              |                                                                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Authors may need more budget                                                                                                                                                                     |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| ·      So that they have time to write                                                                                                                                                           |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| So that they can access writing help                                                                                                                                                             |                                                                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Guideline length and presentation can put authors off                                                                                                                                            | Structure guidance by using navigation menus, subheadings, collapsible sections, modal windows, tool tips that appear on hover, link out to other pages                                                                                                                           |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 1.     Long guidelines appear more complex and time consuming                                                                                                                                    |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 2.     Itemisation can make guidance more digestible, but can also make it harder to get the bigger picture                                                                                      |                                                                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Authors have opinions on how the guidance could be improved including how to make it clearer, and whether items should be rearranged, separated, combined, added or removed.                     | Provide ways for authors to give feedback to guideline developers                                                                                                                                                                                                                 |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Guidelines are more useful to less experienced researchers, but less experienced researchers find them harder to use - S                                                                         | Make guidance easier to understand                                                                                                                                                                                                                                                |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 1.     Experienced authors can feel patronized by checklists                                                                                                                                     | Be mindful of language that may appear patronizing or prescriptive                                                                                                                                                                                                                |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  | Allow authors to give feedback on guidelines, so as to cultivate a feeling of community ownership                                                                                                                                                                                 |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Researchers may feel that guideline (or checklist) compliance is the responsibility of the editor or reviewer                                                                                    | Add an FAQ item explaining why reporting is the responsibility of the author                                                                                                                                                                                                      |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Authors may encounter guidelines late in their writing process                                                                                                                                   | Build user journeys that encourage authors to use guidance earlier next time (like when you buy something from an online business for the first time, they then work hard to gain your custom again)                                                                              |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 1.     The balance of costs vs benefits is at its worst when reporting guidelines are used late                                                                                                  | Instruct authors on when and how to best use guidance                                                                                                                                                                                                                             |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 2.     Authors may be reluctant to change their work once they are ready to submit. They lack time and motivation and it may be awkward for them to send a draft back to their co-authors.       | Provide case studies                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 3.     Authors want to be told to use reporting guidelines earlier in their research pipeline                                                                                                    |                                                                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Authors may need to change their work practices to use reporting guidance                                                                                                                        | Training in writing, workflows and scientific principles                                                                                                                                                                                                                          |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 1.     Authors may not know how to fit reporting guidelines into their writing process (e.g. structuring / drafting / editing), or may not have a writing process at all - E                     | Provide case studies that showcase researchers with a range of experiences, including experienced researchers who have benefited by changing their practices                                                                                                                      |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 2.     Authors may not know how to write / communicate clearly – E, S                                                                                                                            |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 3.     Authors may not have access to help from within their institution (e.g. a publications coordinator or research integrity training)                                                        |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 4.     Authors may not know how a team can use reporting guidelines in practice - E                                                                                                              |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 5.     Authors may be stuck in their ways, not be open to new ways of working – E                                                                                                                |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| Authors may never develop a habit of using guidance, or of searching for guidance as the first step of writing                                                                                   |                                                                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Researchers may be more likely to use a reporting guideline if they see others in their field doing it, or if it becomes a norm                                                                  | Provide “social proof” e.g. number of downloads, citations, or visits                                                                                                                                                                                                             |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  | Build discussion forums so that researchers can see others using and talking about the guidance                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  | Encourage authors to cite guidelines in their manuscripts                                                                                                                                                                                                                         |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Authors may be asked to remove guideline content by co-authors, editors or reviewers                                                                                                             | Provide template responses to counteract common objections from others                                                                                                                                                                                                            |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Authors may feel that good reporting is too much work or takes too long, especially in the face of objection from others – E                                                                     | Provide good examples of other researchers that have found RGs useful                                                                                                                                                                                                             |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  | Provide good examples of reports that were written using a RG to showcase quality                                                                                                                                                                                                 |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  | Capture authors earlier in their research pipeline when the RG will be of most benefit and least cost                                                                                                                                                                             |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  | Create spaces for authors to connect with other authors to celebrate and share experiences e.g. forums, meetings, tea clubs, clinics both in real life and virtual                                                                                                                |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Authors may struggle to use guidelines that are out of date (compared to other guidance or compared to current research standards) – S                                                           | Make it easier for guideline developers to update guidance                                                                                                                                                                                                                        |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  | Minor updates could be made without publishing a new article                                                                                                                                                                                                                      |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| A guideline’s scope can be too broad, too narrow, or poorly defined – S                                                                                                                          |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 1.     If the scope of a guideline is too broad, it can become long or filled with optional items – S                                                                                            |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 2.     If the scope is too narrow, it may not be applicable to many studies – S                                                                                                                  |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 3.     If the scope is undefined authors won’t know whether the guidance applies to them – S                                                                                                     |                                                                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Researchers want design advice, but putting it in the reporting guidance may not be a good solution                                                                                              |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 1.     Assumptions about the design choices narrow the scope of the guidance and can make checklists appear restrictive                                                                          |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 2.     Covering all design options lengthens the guidance and creates optional reporting items, adding complexity                                                                                |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 3.     Including design advice makes the reporting guidance longer                                                                                                                               |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 4.     Including advice on good vs bad design may deter transparency if the author has deviated from best practice.                                                                              |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 5.     Authors want links to further resources                                                                                                                                                   |                                                                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Authors must reconcile multiple sets of guidelines                                                                                                                                               |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 1.     Authors must adhere to journal guidelines, multiple reporting guidelines (e.g. PRISMA + PRISMA-Abstracts + PRISMA-S) and other best practice guidelines (like NIH principles)             |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 2.     Guidelines can contradict each other e.g. journal guidelines vs reporting guidelines on abstract structure                                                                                |                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
| 3.     Using multiple guidelines increases complexity and costs                                                                                                                                  |                                                                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

\elandscape