## Introduction

Having defined intervention components and built a prototype (chapter {{< var chapters.defining-content >}}) I wanted to refine the home page and SRQR guidance page (which I refer to as "the website" in this chapter) by getting feedback from authors. 

The MRC guidance on complex interventions, the Person Based Approach, and the Behaviour Change Wheel all stress the importance of including service users in the design of complex interventions [@skivingtonNewFrameworkDeveloping2021; @michieBehaviourChangeWheel2011; @yardleyPersonBasedApproachIntervention2015]. Service users can help identify deficiencies which, if addressed, would make the intervention more successful @skivingtonNewFrameworkDeveloping2021. Involving service users can also help researchers better understand influences, and whether intervention components are functioning as intended.

In this study, I wanted to address limitations I had identified my thematic synthesis (chapter {{< var chapters.synthesis >}}), where I found testing reporting guidelines with users is rarely done, and often suffers from thin description and unrepresentative participants lacking diversity. In contrast, I wanted to obtain rich data from a diverse group of authors. In chapter {{< var chapters.defining-content >}} I positioned SRQR as a good guideline to test with users because its wide scope includes qualitative methods used by many researchers, from many fields, with varying levels of experience. Thus SRQR offered potential to recruit a diverse sample.

I did not aspire to perfect the website as I, like many in software developers, did not believe an optimal design exists. Variation between users, evolving trends, changing technological and contextual landscape means that a one-size-fits-all optimised design is unlikely @wallachUserCenteredDesignWhy2012. However, although perfection does not exist, designs can none-the-less be improved through feedback and many designers use an iterative process. The purpose of this study was to collect evidence to inform future iterations. Instead of asking authors to suggest improvements (I suspect this strategy would have led to superficial suggestions or blank faces), I was more interested in identifying _deficiencies_. I defined a deficiency as any website element that, if modified, could better facilitate the website's intended target behaviour (for researchers to use reporting guidance as early as possible in their research pipeline). I used the term _deficiency_ over and above _barrier_ or _facilitator_ because it includes both (if a facilitator could be improved, it is deficient). In the future, EQUATOR and I will be able to identify modifications to address these deficiencies.
