## Appendix {{< var appendix.pilot_participant_information >}}: Participant information sheet for author interviews {.appendix #app-pilot-participant-information}

James  Harwood
DPhil Candidate in Musculoskeletal Sciences
Nuffield Department of Orthopaedics, Rheumatology and Musculoskeletal Sciences
Botnar Research Centre, University of Oxford 
Email: james.harwood@stx.ox.ac.uk

### Seeking feedback on a website for researchers {.unnumbered}

### Participant information sheet

#### What is the purpose of this study and why are we inviting you?

We are looking for feedback on a website from people that perform qualitative research.

#### Who is conducting the study?

This research is being conducted by researchers at the University of Oxford, and lead by James Harwood, a PhD student, supported by a grant from Cancer Research UK and supervised by Professor Gary Collins.

#### What will happen to me if I take part?

You will be invited to attend 2 online interviews within a month of each other, with a short reading task in between. Each interview will last around 45 minutes and you will be given a $50 (USD) voucher after the second interview. This will be an Amazon voucher for participants from Europe and the US. Participants from elsewhere will be able to suggest another appropriate voucher provider. 

In the first interview we will ask about your opinions of the website and ask you to navigate it to find information.

You will then have a month to read a small section of the website and annotate any parts that you like or dislike with “+” and “-“ signs. You will be asked to use the website whilst writing a piece of research and we will ask you to share an excerpt of your writing.

In a second interview, we will ask about your writing, annotations and experiences using the website.
 
Once we have completed all interviews, you will have an opportunity to comment on our findings. 

#### Do I have to take part?

Participation is voluntary and you can withdraw at any point, including during the interview, by notifying the project lead (james.harwood@stx.ox.ac.uk). If you choose to leave before completing both interviews and the writing task, you will not receive a voucher. 

#### How will my data be used?

We will collect your name and email to communicate with you through the duration of the study. We will record the video of your interview to refer to during data analysis. We will ask for examples of your work to observe how you have interpreted the website content.  

#### What happens to the data provided?

The information we acquire during the study is the research data.  Any research data from which you can be identified, such as your contact details, consent record and video recording, is known as personal data. All data will be stored on secure servers at the University of Oxford and will be held by and accessible to the research team. 

Personal data: Your contact details will be deleted as soon as the research is finished. We use Zoom to record interview sessions and a secure third-party software called Trint to turn video recordings into anonymised transcripts. Once these transcripts are made, all data will be deleted from Trint and Zoom within 6 months. 

Research data and consent records will be stored for at least 3 years after publication or public release of the work of the research. Transcripts and writing samples will be anonymised. Responsible members of the University of Oxford may be given access to data for monitoring and/or audit of the research. 
 
We would like your permission to use short, anonymised quotes from your interview in our publications and research presentations. All personal information that could identify you will be removed or changed before doing so. We will not use quotes from any writing samples you provide. 

#### Will the research be published?

The research may be published in a student thesis, academic publications, and shared in academic presentations. The student thesis will be deposited both in print and online in the Oxford University Research Archive where it will be publicly available to facilitate its use in future research.
 
#### Who is funding the research?

This research is funded by Cancer Research UK.
 
#### Who has reviewed this study?

This study has been reviewed by the University of Oxford Central University Research Ethics Committee who considered it to be a service evaluation. Therefore, ethical approval was not required.  

Who do I contact if I have a concern about the study or if I wish to complain?
If you have a concern about this study, please email james.harwood@stx.ox.ac.uk who will acknowledge your concern within 10 working days and give you an indication of how it will be dealt with. If you remain unhappy or wish to make a formal complaint, please contact the Chair of the Medical Sciences Interdivisional Research Ethics Committee at the University of Oxford who will seek to resolve the matter as soon as possible. 

Email: ethics@medsci.ox.ac.uk; Address: Research Services, University of Oxford, Boundary Brook House, Churchill Drive, Headington, Oxford OX3 7GB.
 
#### Data Protection

The University of Oxford is the data controller with respect to your personal data, and as such will determine how your personal data is used in the study.

The University will process your personal data for the purpose of the research outlined above.  Research is a task that is performed in the public interest.

Further information about your rights with respect to your personal data is available from https://compliance.admin.ox.ac.uk/individual-rights.
 
#### Further Information and Contact Details

If you would like to discuss this study with someone beforehand (or if you have questions afterwards), please contact:
 
James Harwood
DPhil Candidate in Musculoskeletal Sciences
Nuffield Department of Orthopaedics, Rheumatology and Musculoskeletal Sciences, Botnar Research Centre, University of Oxford 
University email: james.harwood@stx.ox.ac.uk
