## SRQR Checklist for chapter {{< var chapters.focus-groups >}} {.appendix}

| No. | Item                                                                                         | Description                                                                                                                                                                                                                                                                                                                                      | Location                                                                                     |
|-----------|-----------|-----------|----------------------------------------------|
| 1   | Title                                                                                        | Concise description of the nature and topic of the study. Identifying the study as qualitative or indicating the approach (e.g., ethnography, grounded theory) or data collection methods (e.g., interview, focus group) is recommended.                                                                                                         | Chapter Title                                                                                |
| 2   | Abstract                                                                                     | Summary of key elements of the study using the abstract format of the intended publication; typically includes background, purpose, methods, results, and conclusions                                                                                                                                                                            | N/A                                                                                          |
| 3   | Problem Formation                                                                            | Description and significance of the problem/phenomenon studied; review of relevant theory and empirical work; problem statement                                                                                                                                                                                                                  | Introduction para. 2; Previous chapters                                                      |
| 4   | Purpose or research question                                                                 | Purpose of the study and specific objectives or questions                                                                                                                                                                                                                                                                                        | Introduction para. 2; Methods para. 1                                                        |
| 5   | Qualitative approach and research paradigm                                                   | Qualitative approach (e.g., ethnography, grounded theory, case study, phenomenology, narrative research) and guiding theory if appropriate; identifying the research paradigm (e.g., postpositivist, constructivist/ interpretivist) is also recommended; rationale\*                                                                            | Methods para. 1–6; Reflexivity & Trust para. 1                                               |
| 6   | Researcher characteristics and reflexivity                                                   | Researchers’ characteristics that may influence the research, including personal attributes, qualifications/experience, relationship with participants, assumptions, and/or presuppositions; potential or actual interaction between researchers’ characteristics and the research questions, approach, methods, results, and/or transferability | Reflexivity and Trust; Reflections on This Chapter; Chapter {{< var chapters.reflexivity >}} |
| 7   | Context                                                                                      | Setting/site and salient contextual factors; rationale\*                                                                                                                                                                                                                                                                                         | Methods, Focus Group Sessions para. 1                                                        |
| 8   | Sampling strategy                                                                            | How and why research participants, documents, or events were selected; criteria for deciding when no further sampling was necessary (e.g., sampling saturation); rationale\*                                                                                                                                                                     | Methods, Sampling                                                                            |
| 9   | Ethical issues pertaining to human subjects                                                  | Documentation of approval by an appropriate ethics review board and participant consent, or explanation for lack thereof; other confidentiality and data security issues                                                                                                                                                                         | Methods, Ethics and Data Management                                                          |
| 10  | Data collection methods                                                                      | Types of data collected; details of data collection procedures including (as appropriate) start and stop dates of data collection and analysis, iterative process, triangulation of sources/methods, and modification of procedures in response to evolving study findings; rationale\*                                                          | Methods, Focus Group Sessions                                                                |
| 11  | Data collection instruments and technologies                                                 | Description of instruments (e.g., interview guides, questionnaires) and devices (e.g., audio recorders) used for data collection; if/how the instrument(s) changed over the course of the study                                                                                                                                                  | Methods, Materials                                                                           |
| 12  | Units of study                                                                               | Number and relevant characteristics of participants, documents, or events included in the study; level of participation (could be reported in results)                                                                                                                                                                                           | Results, Units of Study                                                                      |
| 13  | Data processing                                                                              | Methods for processing data prior to and during analysis, including transcription, data entry, data management and security, verification of data integrity, data coding, and anonymization/deidentification of excerpts                                                                                                                         | Methods, Processing and analysis                                                             |
| 14  | Data analysis                                                                                | Process by which inferences, themes, etc., were identified and developed, including the researchers involved in data analysis; usually references a specific paradigm or approach; rationale\*                                                                                                                                                   | Methods, Processing and analysis                                                             |
| 15  | Techniques to enhance trustworthiness                                                        | Techniques to enhance trustworthiness and credibility of data analysis (e.g., member checking, audit trail, triangulation); rationale\*                                                                                                                                                                                                          | Methods, Reflexivity and Trust para. 2 and @tbl-trust                                        |
| 16  | Synthesis and interpretation                                                                 | Main findings (e.g., interpretations, inferences, and themes); might include development of a theory or model, or integration with prior research or theory                                                                                                                                                                                      | Results, Synthesis and Summary                                                               |
| 17  | Links to empirical data                                                                      | Evidence (e.g., quotes, field notes, text excerpts, photographs) to substantiate analytic findings                                                                                                                                                                                                                                               | Results, Synthesis and Summary                                                               |
| 18  | Integration with prior work, implications, transferability, and contribution(s) to the field | Short summary of main findings; explanation of how findings and conclusions connect to, support, elaborate on, or challenge conclusions of earlier scholarship; discussion of scope of application/ generalizability; identification of unique contribution(s) to scholarship in a discipline or field                                           | Discussion, Summary of Results & Implications                                                |
| 19  | Limitations                                                                                  | Trustworthiness and limitations of findings                                                                                                                                                                                                                                                                                                      | Discussion, Limitations                                                                      |
| 20  | Conflicts of interest                                                                        | Potential sources of influence or perceived influence on study conduct and conclusions; how these were managed                                                                                                                                                                                                                                   | See chapter {{< var chapters.reflexivity >}}                                                 |
| 21  | Funding                                                                                      | Sources of funding and other support; role of funders in data collection, interpretation, and reporting                                                                                                                                                                                                                                          | See Acknowledgements                                                                         |

: SRQR Checklist @obrienStandardsReportingQualitative2014 {#tbl-srqr-focus-groups tbl-colwidths="\[5, 25, 35, 35\]"}