## PRISMA-S Checklist for chapter {{< var chapters.synthesis >}} {.appendix}

| No. | Item                          | Description                                                                                                                                                                                                                                                        | Location                                                                         |
|-------|----------|--------------|-------------------------------------------------------|
| 1   | Database name                 | Name each individual database searched, stating the platform for each.                                                                                                                                                                                             | See Methods @tbl-info-sources and Appendix {{< var appendix.search >}}           |
| 2   | Multi-database searching      | If databases were searched simultaneously on a single platform, state the name of the platform, listing all of the databases searched.                                                                                                                             | See Methods @tbl-info-sources and Appendix {{< var appendix.search >}}           |
| 3   | Study registries              | List any study registries searched.                                                                                                                                                                                                                                | See Methods @tbl-info-sources and Appendix {{< var appendix.search >}}           |
| 4   | Online resources and browsing | Describe any online or print source purposefully searched or browsed (e.g., tables of contents, print conference proceedings, web sites), and how this was done.                                                                                                   | See Methods @tbl-info-sources and Appendix {{< var appendix.search >}}           |
| 5   | Citation searching            | Indicate whether cited references or citing references were examined, and describe any methods used for locating cited/citing references (e.g., browsing reference lists, using a citation index, setting up email alerts for references citing included studies). | See Methods, Approach to searching and data sources                              |
| 6   | Contacts                      | Indicate whether additional studies or data were sought by contacting authors, experts, manufacturers, or others.                                                                                                                                                  | See Methods, Approach to searching and data sources                              |
| 7   | Other methods                 | Describe any additional information sources or search methods used.                                                                                                                                                                                                | No other methods                                                                 |
| 8   | Full search strategies        | Include the search strategies for each database and information source, copied and pasted exactly as run.                                                                                                                                                          | Appendix {{< var appendix.search >}}                                             |
| 9   | Limits and restrictions       | Specify that no limits were used, or describe any limits or restrictions applied to a search (e.g., date or time period, language, study design) and provide justification for their use.                                                                          | See Methods, Inclusions and exclusion criteria.                                  |
| 10  | Search filters                | Indicate whether published search filters were used (as originally designed or modified), and if so, cite the filter(s) used.                                                                                                                                      | See Methods, Electronic search strategy                                          |
| 11  | Prior work                    | Indicate when search strategies from other literature reviews were adapted or reused for a substantive part or all of the search, citing the previous review(s).                                                                                                   | See Methods, Electronic search strategy                                          |
| 12  | Updates                       | Report the methods used to update the search(es) (e.g., rerunning searches, email alerts).                                                                                                                                                                         | No update done.                                                                  |
| 13  | Dates of searches             | For each search strategy, provide the date when the last search occurred.                                                                                                                                                                                          | See Methods, @tbl-info-sources                                                   |
| 14  | Peer review                   | Describe any search peer review process.                                                                                                                                                                                                                           | See Methods, Electronic Search Strategy and Appendix {{< var appendix.search >}} |
| 15  | Total records                 | Document the total number of records identified from each database and other information sources.                                                                                                                                                                  | See Results, @fig-prisma-flow-diagram                                            |
| 16  | Deduplication                 | Describe the processes and any software used to deduplicate records from multiple database searches and other information sources.                                                                                                                                 | See Methods @tbl-info-sources                                                    |

: PRISMA-S Checklist for chapter {{< var chapters.synthesis >}} @rethlefsenPRISMASExtensionPRISMA2021 {#tbl-srqr tbl-colwidths="\[5, 25, 35, 35\]"}