## Search strategies {.appendix #app-search-strategies .unnumbered}

I did not seek any external peer review of my search. I did not record the database versions at the time of searching due to an oversight. I performed forward and backwards citation searching but found no additional records. I did not set up email alerts.

### Ovid search strategy

Databases: Medline, Embase, AMED, PsycINFO.

Search date: 08/12/2021

I used a federated search. The *kw* field does not exist in PsycINFO or AMED and so was ignored by these databases. The *tw* field does not exist in AMED either and was mapped to *af* instead.

1.  ((reporting or writ\$ or author\$) adj2 (checklist\$ or statement\$ or guid\$ or template\$ or standard\$ or recommendation\$)).ti,kw.

2.  ((consort\$ or strobe\$ or stard\$ or prisma\$ or moose\$ or squire\$ or arrive\$ or remark\$ or tripod\$ or cheers\$ or spirit\$ or srqr\$ or coreq\$) adj3 (guid\$ or statement\$ or checklist\$)).ti,kw.

3.  (experience\$ or interview\$ or survey\$ or questionnaire\$ or \"focus group\$\" or facilitat\$ or barrier\$).af.

4.  qualitative.tw.

5.  1 or 2

6.  3 or 4

7.  5 and 6

Platform-specific filter applied: 1996 -- current year

### Global Index Medicus & SciELO search strategy

Databases: Latin American and Caribbean Health Sciences Literature, African Index Medicus, Western Pacific Region Index Medicus, Index Medicus for South-East Asia Region, and Index Medicus for the Eastern Mediterranean Region, searched using Global Index Medicus (https://www.globalindexmedicus.net/); Scientific Electronic Library Online (<https://scielo.org/en/>).

Search date: 08/12/2021

ti:(((reporting OR writ\* OR author\*) AND (checklist\* OR statement\* OR guid\* OR template\* OR standard\* OR recommendation\* OR experience\* OR interview\* OR survey\* OR questionnaire\* OR \"focus group\*\" OR facilitat\* OR barrier\* OR qualitative\*)))

Platform-specific filter applied: 1996 -- current year

### Chinese Biomedical Literature Database

Database URL: <https://www.imicams.ac.cn/>

Search Date: 25/10/2021

1\. 报告 OR 撰写 OR 作者

2\. 清单 OR 声明 OR 指导 OR 规范 OR 指南 OR 共识 OR 模板 OR 标准 OR 推荐意见

3\. CONSORT OR PRISMA OR STROBE OR SPIRIT OR STARD OR SRQR OR ARRIVE OR SQUIRE OR CHEERS OR TRIPOD OR COREQ

4\. 经历 OR 体验 OR 访谈OR 调查 OR 问卷调查 OR 焦点小组 OR 焦点群众

5\. 促进 OR 阻碍

6\. 质性研究 OR 定性研究

7\. (#2) AND (#1)

8\. (#7) OR (#3)

9\. (#6) OR (#5) OR (#4)

10\. (#9) AND (#8)

11\. ((#9) AND (#8)) AND (\"循证文献\"[文献类型] OR \"临床试验\"[文献类型])

### China National Knowledge Infrastructure

Database URL: <https://www.cnki.net/>

Search Date: 25/10/2021

( ( ( TI = \'报告\' OR TI = \'撰写\' OR TI = \'作者\') AND (TI = \'清单\' OR TI = \'声明\' OR TI = \'指导\' OR TI = \'规范\' OR TI = \'指南\' OR TI = \'共识\' OR TI = \'模板\' OR TI = \'标准\' OR TI = \'推荐意见\' ) ) OR ( TI = \'CONSORT\' OR TI = \'STROBE\' OR TI = \'PRISMA\' OR TI = \'SPIRIT\' OR TI = \'STARD\' OR TI = \'SRQR\' OR TI = \'ARRIVE\' OR TI = \'SQUIRE\' OR TI = \'CHEERS\' OR TI = \'TRIPOD\' OR TI = \'COREQ\' ) ) AND (TI = \'经历\' OR TI = \'体验\' OR TI = \'访谈\' OR TI = \'调查\' OR TI = \'问卷调查\' OR TI = \'焦点群众\' OR TI = \'焦点小组\' OR TI = \'促进\' OR TI = \'阻碍\' OR TI = \'质性研究\' OR TI = \'定性研究\' )

### Wanfang Data

Database URL: http://www.wanfangdata.com/

(((题名或关键词:(报告 or 撰写 or 作者)) and (题名或关键词:(清单 or 声明 or 指导 or 规范 or 指南 or 共识 or 模板 or 标准 or 推荐意见))) or (题名或关键词:(CONSORT or STROBE or STARD or PRISMA or MOOSE or SQUIRE or ARRIVE or REMARK or TRIPOD or CHEERS or SPIRIT or SRQR or COREQ))) and (题名或关键词:(经历 or 体验 or 访谈 or 访问 or 采访 or 调查 or 问卷调查 or 焦点小组 or 焦点群众 or 促进 or 阻碍 or 质性研究 or 定性研究))

### VIP Chinese Medical Journal Database

Database URL: http://www.cqvip.com/

(((M=(报告 OR 撰写 OR 作者)) AND (M=(清单 OR 声明 OR 指导 OR 规范 OR 指南 OR 共识 OR 模板 OR 标准 OR 推荐意见))) OR (M=(CONSORT OR PRISMA OR STROBE OR SPIRIT OR STARD OR SRQR OR ARRIVE OR SQUIRE OR CHEERS OR TRIPOD OR COREQ))) AND (M=(体验 OR 访谈 OR 调查 OR 问卷调查 OR 焦点群众 OR 焦点小组 OR 质性研究 OR 定性研究))

### OSF

URL: <https://osf.io/>

Search Date: 15/12/2021

title:(((reporting OR writ\* OR author\*) AND (checklist\* OR statement\* OR guid\* OR template\* OR standard\* OR recommendation\* OR experience\* OR interview\* OR survey\* OR questionnaire\* OR \"focus group\*\" OR facilitat\* OR barrier\* OR qualitative\*)))

### Methods in Research on Research 

URL: http://miror-ejd.eu/publications/

Search Date: 14/12/2021

I manually searched the list of publications.
